import type { ExpenseCategoryInput, ExpenseInput, PurchaseInvoiceInput, SupplierInput, SupplierPaymentInput } from '@fuelledger/shared';
import { Prisma } from '@prisma/client';
import { AppError } from '../../lib/errors.js';
import { prisma } from '../../lib/prisma.js';
import { collectionAccount, postJournal } from '../accounting/service.js';

const invoiceInclude={supplier:{select:{id:true,name:true,code:true,paymentTerms:true}},station:{select:{id:true,name:true,code:true}},lines:{include:{product:{select:{id:true,name:true,code:true,unit:true,tankLinked:true}}}},payments:{orderBy:{paidAt:'desc' as const}},receipt:{select:{id:true,receivedAt:true}},attachments:{select:{id:true,fileName:true,mimeType:true,size:true}},createdBy:{select:{name:true}}} as const;
const expenseInclude={station:{select:{id:true,name:true,code:true}},category:true,attachments:{select:{id:true,fileName:true,mimeType:true,size:true}},createdBy:{select:{name:true}}} as const;
const outstanding=(invoice:{totalAmount:Prisma.Decimal;payments:Array<{amount:Prisma.Decimal}>})=>Number(invoice.totalAmount)-invoice.payments.reduce((sum,row)=>sum+Number(row.amount),0);
export async function bootstrap(organizationId:string,stationIds?:string[]){const startOfToday=new Date();startOfToday.setHours(0,0,0,0);const [suppliers,invoices,stations,products,categories,expenses]=await Promise.all([
 prisma.supplier.findMany({where:{organizationId},orderBy:[{active:'desc'},{name:'asc'}]}),
 prisma.purchaseInvoice.findMany({where:{organizationId,...(stationIds?{stationId:{in:stationIds}}:{})},take:100,orderBy:{invoiceDate:'desc'},include:invoiceInclude}),
 prisma.station.findMany({where:{organizationId,active:true,...(stationIds?{id:{in:stationIds}}:{})},orderBy:{name:'asc'},select:{id:true,name:true,code:true,configurations:{where:{active:true},take:1,select:{tanks:{where:{status:'ACTIVE'},select:{id:true,code:true,productId:true}}}}}}),
 prisma.product.findMany({where:{organizationId,active:true,inventoryTracked:true},orderBy:{name:'asc'},select:{id:true,name:true,code:true,unit:true,purchasePrice:true,tankLinked:true}}),
 prisma.expenseCategory.findMany({where:{organizationId,active:true},orderBy:{name:'asc'}}),
 prisma.expense.findMany({where:{organizationId,...(stationIds?{stationId:{in:stationIds}}:{})},take:100,orderBy:{incurredAt:'desc'},include:expenseInclude}),
]);const shaped=invoices.map(invoice=>({...invoice,outstanding:outstanding(invoice),overdue:invoice.status!=='PAID'&&invoice.status!=='VOID'&&invoice.dueDate<startOfToday}));return{suppliers,invoices:shaped,stations,products,categories,expenses,summary:{payables:shaped.reduce((sum,x)=>sum+x.outstanding,0),overdue:shaped.filter(x=>x.overdue).reduce((sum,x)=>sum+x.outstanding,0),expensesThisMonth:expenses.filter(x=>{const now=new Date();return x.incurredAt.getMonth()===now.getMonth()&&x.incurredAt.getFullYear()===now.getFullYear()}).reduce((sum,x)=>sum+Number(x.amount),0)}};}
export async function createSupplier(organizationId:string,input:SupplierInput){try{return await prisma.supplier.create({data:{organizationId,...input,email:input.email||null,phone:input.phone||null,taxId:input.taxId||null,address:input.address||null}})}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002')throw new AppError(409,'SUPPLIER_CODE_EXISTS','That supplier code is already in use.');throw error;}}
export async function createCategory(organizationId:string,input:ExpenseCategoryInput){try{return await prisma.expenseCategory.create({data:{organizationId,...input}})}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002')throw new AppError(409,'EXPENSE_CATEGORY_EXISTS','That expense category code is already in use.');throw error;}}
export async function createInvoice(organizationId:string,userId:string,input:PurchaseInvoiceInput){const [station,supplier,products]=await Promise.all([prisma.station.findFirst({where:{id:input.stationId,organizationId,active:true}}),prisma.supplier.findFirst({where:{id:input.supplierId,organizationId,active:true}}),prisma.product.findMany({where:{organizationId,id:{in:input.lines.flatMap(x=>x.productId?[x.productId]:[])},active:true,inventoryTracked:true}})]);if(!station)throw new AppError(404,'STATION_NOT_FOUND','Choose an active station.');if(!supplier)throw new AppError(404,'SUPPLIER_NOT_FOUND','Choose an active supplier.');if(input.receiveNow&&products.length!==new Set(input.lines.map(x=>x.productId)).size)throw new AppError(400,'PRODUCT_NOT_INVENTORIED','Every received invoice line needs an active inventory product.');const subtotal=input.lines.reduce((sum,line)=>sum+line.quantity*line.unitCost,0);const total=subtotal+input.taxAmount;
try{return await prisma.$transaction(async tx=>{const invoice=await tx.purchaseInvoice.create({data:{organizationId,stationId:station.id,supplierId:supplier.id,invoiceNumber:input.invoiceNumber,invoiceDate:new Date(input.invoiceDate),dueDate:new Date(input.dueDate),subtotal:new Prisma.Decimal(subtotal),taxAmount:new Prisma.Decimal(input.taxAmount),totalAmount:new Prisma.Decimal(total),notes:input.notes||null,createdById:userId,lines:{create:input.lines.map(line=>({productId:line.productId||null,description:line.description,quantity:new Prisma.Decimal(line.quantity),unitCost:new Prisma.Decimal(line.unitCost),taxRate:new Prisma.Decimal(line.taxRate),lineTotal:new Prisma.Decimal(line.quantity*line.unitCost)}))},...(input.attachment?{attachments:{create:{fileName:input.attachment.fileName,mimeType:input.attachment.mimeType,size:input.attachment.size,content:Buffer.from(input.attachment.contentBase64,'base64')}}}:{})},include:invoiceInclude});if(input.receiveNow){const receipt=await tx.purchaseReceipt.create({data:{organizationId,stationId:station.id,supplierId:supplier.id,invoiceId:invoice.id,supplierName:supplier.name,referenceNo:invoice.invoiceNumber,receivedAt:invoice.invoiceDate,notes:'Received with purchase invoice',createdById:userId}});for(const line of input.lines){const product=products.find(x=>x.id===line.productId)!;const tank=line.tankId?await tx.tank.findFirst({where:{id:line.tankId,productId:product.id,status:'ACTIVE',configuration:{stationId:station.id,active:true}}}):null;if(line.tankId&&!tank)throw new AppError(400,'TANK_MAPPING_INVALID','The selected tank must hold the invoiced product.');if(product.tankLinked&&!tank)throw new AppError(400,'TANK_REQUIRED',`${product.name} must be received into a configured tank.`);const receiptLine=await tx.receiptLine.create({data:{receiptId:receipt.id,productId:product.id,tankId:tank?.id??null,quantity:line.quantity,unitCost:line.unitCost}});await tx.inventoryLedger.create({data:{organizationId,stationId:station.id,productId:product.id,tankId:tank?.id??null,type:'RECEIPT',quantityDelta:line.quantity,unitCost:line.unitCost,receiptLineId:receiptLine.id,occurredAt:invoice.invoiceDate,createdById:userId}});}}await postJournal(tx,{organizationId,stationId:station.id,createdById:userId,journalDate:invoice.invoiceDate,reference:`PI-${invoice.invoiceNumber}`,description:`Purchase invoice from ${supplier.name}`,sourceType:'PURCHASE_INVOICE',sourceId:invoice.id,lines:[{account:input.receiveNow?'1200':'1220',debit:subtotal},...(input.taxAmount?[{account:'1210',debit:input.taxAmount}]:[]),{account:'2000',credit:total}]});return invoice;});}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002')throw new AppError(409,'INVOICE_EXISTS','This invoice number already exists for the supplier.');throw error;}}
export async function payInvoice(organizationId:string,userId:string,input:SupplierPaymentInput){const invoice=await prisma.purchaseInvoice.findFirst({where:{id:input.invoiceId,organizationId,status:{in:['OPEN','PART_PAID']}},include:{payments:true}});if(!invoice)throw new AppError(404,'INVOICE_NOT_PAYABLE','Choose an open purchase invoice.');if(invoice.stationId!==input.stationId)throw new AppError(400,'PAYMENT_STATION_MISMATCH','The payment station must match the purchase invoice station.');const remaining=outstanding(invoice);if(input.amount>remaining+.001)throw new AppError(400,'PAYMENT_EXCEEDS_DUE','Payment cannot exceed the invoice outstanding.');return prisma.$transaction(async tx=>{const payment=await tx.supplierPayment.create({data:{organizationId,stationId:input.stationId,supplierId:invoice.supplierId,invoiceId:invoice.id,amount:input.amount,paymentMethod:input.paymentMethod,referenceNo:input.referenceNo||null,createdById:userId}});const next=remaining-input.amount;await tx.purchaseInvoice.update({where:{id:invoice.id},data:{status:next<.01?'PAID':'PART_PAID'}});await postJournal(tx,{organizationId,stationId:input.stationId,createdById:userId,journalDate:payment.paidAt,reference:`SP-${payment.id.slice(-8)}`,description:'Supplier payment',sourceType:'SUPPLIER_PAYMENT',sourceId:payment.id,lines:[{account:'2000',debit:input.amount},{account:collectionAccount(input.paymentMethod),credit:input.amount}]});return payment;});}
export async function createExpense(organizationId:string,userId:string,input:ExpenseInput){const [station,category]=await Promise.all([prisma.station.findFirst({where:{id:input.stationId,organizationId,active:true}}),prisma.expenseCategory.findFirst({where:{id:input.categoryId,organizationId,active:true}})]);if(!station||!category)throw new AppError(404,'EXPENSE_CONTEXT_INVALID','Choose an active station and expense category.');return prisma.$transaction(async tx=>{const expense=await tx.expense.create({data:{organizationId,stationId:station.id,categoryId:category.id,description:input.description,amount:input.amount,paymentMethod:input.paymentMethod,incurredAt:new Date(input.incurredAt),referenceNo:input.referenceNo||null,notes:input.notes||null,createdById:userId,...(input.attachment?{attachments:{create:{fileName:input.attachment.fileName,mimeType:input.attachment.mimeType,size:input.attachment.size,content:Buffer.from(input.attachment.contentBase64,'base64')}}}:{})},include:expenseInclude});await postJournal(tx,{organizationId,stationId:station.id,createdById:userId,journalDate:expense.incurredAt,reference:`EXP-${expense.id.slice(-8)}`,description:expense.description,sourceType:'EXPENSE',sourceId:expense.id,lines:[{account:'6100',debit:input.amount},{account:collectionAccount(input.paymentMethod),credit:input.amount}]});return expense;});}
export async function attachment(organizationId:string,id:string){const file=await prisma.attachment.findFirst({where:{id,OR:[{purchaseInvoice:{organizationId}},{expense:{organizationId}}]}});if(!file)throw new AppError(404,'ATTACHMENT_NOT_FOUND','Attachment not found.');return file;}
