import { useState } from 'react';
import { ArrowRight, Check, Droplets } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api, ApiRequestError, type DashboardBootstrap } from '../lib/api';

type Tank = DashboardBootstrap['tankStocks'][number];
const amount=(value:number)=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:1}).format(value);
const recordedToday=(value:string|null,referenceDate:string)=>{if(!value)return false;const reading=new Date(value),today=new Date(referenceDate);return reading.getFullYear()===today.getFullYear()&&reading.getMonth()===today.getMonth()&&reading.getDate()===today.getDate()};

export function FuelTankBank({tanks,asOf}:{tanks:Tank[];asOf:string}){
  const [editing,setEditing]=useState<string|null>(null);const [density,setDensity]=useState('');const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [saved,setSaved]=useState<Record<string,number>>({});
  async function save(tank:Tank){const value=Number(density);if(value<600||value>1200){setError('Enter a density between 600 and 1,200 kg/m³.');return}setSaving(true);setError('');try{await api.recordDensity({stationId:tank.station.id,tankId:tank.id,density:value});setSaved(current=>({...current,[tank.id]:value}));setEditing(null);setDensity('')}catch(item){setError(item instanceof ApiRequestError?item.message:'Unable to save density.')}finally{setSaving(false)}}
  const counters:Record<string,number>={};
  return <section className="fuel-bank"><header><div><span className="eyebrow">Fuel tank stock</span><h2>Live tank levels</h2><p>Levels move automatically with recorded stock.</p></div><Link to="/inventory">Update inventory <ArrowRight/></Link></header>{tanks.length?<div className="fuel-bank-grid">{tanks.map(tank=>{const sequence=(counters[tank.productCode]=(counters[tank.productCode]??0)+1);const colour=tank.productCode==='MS'?'ms':'hsd';const todayDone=saved[tank.id]!==undefined||recordedToday(tank.densityRecordedAt,asOf);const shownDensity=saved[tank.id]??tank.density;return <article className={`fuel-orb-card ${colour}`} key={tank.id}><div className="fuel-orb" aria-label={`${tank.productCode} Tank ${sequence}: ${amount(tank.fillPercent)} percent full`}><span className="fuel-liquid" style={{height:`${tank.fillPercent}%`}}/><span className="fuel-percent">{amount(tank.fillPercent)}%</span></div><div className="fuel-orb-copy"><span className="fuel-product">{tank.productCode}</span><h3>{tank.productCode} Tank {sequence}</h3><dl><div><dt>Current inventory</dt><dd>{amount(tank.bookStock)} L</dd></div><div><dt>Total capacity</dt><dd>{amount(tank.workingCapacity)} L</dd></div><div><dt>Selling price</dt><dd>₹{amount(tank.sellingPrice)}/L</dd></div><div className="density-cell"><dt>Morning density</dt><dd>{todayDone&&shownDensity!==null?<span className="density-saved"><Check/> {amount(shownDensity)} kg/m³</span>:editing===tank.id?<span className="density-entry"><input autoFocus type="number" min="600" max="1200" step=".001" value={density} onChange={event=>setDensity(event.target.value)} placeholder="e.g. 745"/><button disabled={saving} onClick={()=>void save(tank)}>{saving?'Saving…':'Save'}</button><button onClick={()=>{setEditing(null);setError('')}}>Cancel</button>{error&&<small>{error}</small>}</span>:<button className="density-due" onClick={()=>{setEditing(tank.id);setDensity('');setError('')}}>Enter morning density</button>}</dd></div></dl></div></article>})}</div>:<div className="owner-all-clear compact"><Droplets/><h3>No MS or HSD tanks configured</h3><p>Add fuel tanks in Petrol Pump setup to see them here.</p></div>}</section>;
}
