import { AccountType, Prisma } from '@prisma/client';
import { AppError } from '../../lib/errors.js';
import { prisma } from '../../lib/prisma.js';

type Tx=Prisma.TransactionClient;type PostingLine={account:string;debit?:number|Prisma.Decimal;credit?:number|Prisma.Decimal;memo?:string};
const defaults:Array<{code:string;name:string;type:AccountType}>=[
  {code:'1000',name:'Cash on Hand',type:'ASSET'},{code:'1010',name:'UPI Clearing',type:'ASSET'},{code:'1020',name:'Card Clearing',type:'ASSET'},{code:'1030',name:'Other Collections',type:'ASSET'},
  {code:'1100',name:'Accounts Receivable',type:'ASSET'},{code:'1200',name:'Inventory',type:'ASSET'},{code:'1210',name:'Input Tax Credit',type:'ASSET'},{code:'1220',name:'Goods in Transit',type:'ASSET'},
  {code:'2000',name:'Accounts Payable',type:'LIABILITY'},{code:'4000',name:'Product Revenue',type:'REVENUE'},{code:'4010',name:'Service Revenue',type:'REVENUE'},
  {code:'5000',name:'Cost of Goods Sold',type:'EXPENSE'},{code:'5100',name:'Inventory Variance',type:'EXPENSE'},{code:'6100',name:'Operating Expenses',type:'EXPENSE'},
];
export async function ensureChart(tx:Tx,organizationId:string){await Promise.all(defaults.map(account=>tx.chartAccount.upsert({where:{organizationId_code:{organizationId,code:account.code}},update:{},create:{organizationId,...account}})));return tx.chartAccount.findMany({where:{organizationId}});}
export const collectionAccount=(method:string)=>method==='CASH'?'1000':method==='UPI'?'1010':method==='CARD'?'1020':method==='CREDIT'||method==='FLEET'?'1100':'1030';
export async function postJournal(tx:Tx,input:{organizationId:string;stationId?:string|null;createdById?:string|null;journalDate?:Date;reference:string;description:string;sourceType:string;sourceId:string;lines:PostingLine[]}){const accounts=await ensureChart(tx,input.organizationId);const ids=new Map(accounts.map(x=>[x.code,x.id]));const debit=input.lines.reduce((sum,line)=>sum.add(line.debit??0),new Prisma.Decimal(0));const credit=input.lines.reduce((sum,line)=>sum.add(line.credit??0),new Prisma.Decimal(0));if(!debit.equals(credit)||debit.lessThanOrEqualTo(0))throw new AppError(500,'JOURNAL_UNBALANCED','Accounting journal is not balanced.');return tx.journal.create({data:{organizationId:input.organizationId,stationId:input.stationId??null,createdById:input.createdById??null,journalDate:input.journalDate??new Date(),reference:input.reference,description:input.description,sourceType:input.sourceType,sourceId:input.sourceId,lines:{create:input.lines.map(line=>{const accountId=ids.get(line.account);if(!accountId)throw new AppError(500,'ACCOUNT_MISSING',`Account ${line.account} is not configured.`);return{accountId,debit:line.debit??0,credit:line.credit??0,memo:line.memo??null}})}}});}
export async function bootstrap(organizationId:string,stationIds?:string[]){await prisma.$transaction(tx=>ensureChart(tx,organizationId));const scope=stationIds?{stationId:{in:stationIds}}:{};const [accounts,journals,invoices]=await Promise.all([prisma.chartAccount.findMany({where:{organizationId},orderBy:{code:'asc'},include:{journalLines:{where:{journal:scope}}}}),prisma.journal.findMany({where:{organizationId,...scope},take:100,orderBy:[{journalDate:'desc'},{createdAt:'desc'}],include:{station:{select:{name:true,code:true}},createdBy:{select:{name:true}},lines:{include:{account:{select:{code:true,name:true,type:true}}}}}}),prisma.purchaseInvoice.findMany({where:{organizationId,...scope,status:{not:'VOID'}},take:100,orderBy:[{invoiceDate:'desc'},{createdAt:'desc'}],select:{id:true,invoiceNumber:true,invoiceDate:true,dueDate:true,totalAmount:true,status:true,supplier:{select:{name:true,code:true}},station:{select:{name:true,code:true}},payments:{select:{amount:true}}}})]);const ledger=accounts.map(account=>{const debit=account.journalLines.reduce((sum,line)=>sum+Number(line.debit),0),credit=account.journalLines.reduce((sum,line)=>sum+Number(line.credit),0);const normal=account.type==='ASSET'||account.type==='EXPENSE'?debit-credit:credit-debit;return{id:account.id,code:account.code,name:account.name,type:account.type,debit,credit,balance:normal};});const trial={debit:ledger.reduce((sum,x)=>sum+x.debit,0),credit:ledger.reduce((sum,x)=>sum+x.credit,0)};const today=new Date();today.setHours(0,0,0,0);const payables=invoices.map(invoice=>{const total=Number(invoice.totalAmount),paid=invoice.payments.reduce((sum,payment)=>sum+Number(payment.amount),0),outstanding=Math.max(0,total-paid);return{id:invoice.id,invoiceNumber:invoice.invoiceNumber,invoiceDate:invoice.invoiceDate,dueDate:invoice.dueDate,total,paid,outstanding,status:invoice.status,overdue:outstanding>.01&&invoice.dueDate<today,supplier:invoice.supplier,station:invoice.station};});return{accounts:ledger,journals,payables,trial};}
