CREATE TYPE "CustomerType" AS ENUM ('CREDIT', 'FLEET');
CREATE TYPE "CustomerLedgerType" AS ENUM ('SALE', 'RECEIPT', 'ADJUSTMENT');
ALTER TABLE "sales" ADD COLUMN "customer_id" TEXT, ADD COLUMN "vehicle_id" TEXT;
CREATE TABLE "customers" ("id" TEXT NOT NULL,"organization_id" TEXT NOT NULL,"name" TEXT NOT NULL,"code" TEXT NOT NULL,"type" "CustomerType" NOT NULL DEFAULT 'CREDIT',"phone" TEXT,"email" TEXT,"tax_id" TEXT,"billing_address" TEXT,"credit_limit" DECIMAL(14,2) NOT NULL DEFAULT 0,"credit_days" INTEGER NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT true,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "customers_pkey" PRIMARY KEY ("id"));
CREATE TABLE "vehicles" ("id" TEXT NOT NULL,"customer_id" TEXT NOT NULL,"number" TEXT NOT NULL,"label" TEXT,"active" BOOLEAN NOT NULL DEFAULT true,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "vehicles_pkey" PRIMARY KEY ("id"));
CREATE TABLE "customer_receipts" ("id" TEXT NOT NULL,"organization_id" TEXT NOT NULL,"station_id" TEXT NOT NULL,"customer_id" TEXT NOT NULL,"amount" DECIMAL(14,2) NOT NULL,"payment_method" "PaymentMethod" NOT NULL,"reference_no" TEXT,"notes" TEXT,"received_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"created_by_id" TEXT NOT NULL,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "customer_receipts_pkey" PRIMARY KEY ("id"));
CREATE TABLE "customer_ledger" ("id" TEXT NOT NULL,"organization_id" TEXT NOT NULL,"station_id" TEXT NOT NULL,"customer_id" TEXT NOT NULL,"type" "CustomerLedgerType" NOT NULL,"amount" DECIMAL(14,2) NOT NULL,"sale_id" TEXT,"receipt_id" TEXT,"description" TEXT NOT NULL,"due_date" TIMESTAMP(3),"occurred_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"created_by_id" TEXT NOT NULL,CONSTRAINT "customer_ledger_pkey" PRIMARY KEY ("id"));
CREATE INDEX "customers_organization_id_active_idx" ON "customers"("organization_id", "active");
CREATE UNIQUE INDEX "customers_organization_id_code_key" ON "customers"("organization_id", "code");
CREATE UNIQUE INDEX "vehicles_customer_id_number_key" ON "vehicles"("customer_id", "number");
CREATE INDEX "customer_receipts_customer_id_received_at_idx" ON "customer_receipts"("customer_id", "received_at");
CREATE UNIQUE INDEX "customer_ledger_sale_id_key" ON "customer_ledger"("sale_id");
CREATE UNIQUE INDEX "customer_ledger_receipt_id_key" ON "customer_ledger"("receipt_id");
CREATE INDEX "customer_ledger_customer_id_occurred_at_idx" ON "customer_ledger"("customer_id", "occurred_at");
CREATE INDEX "customer_ledger_customer_id_due_date_idx" ON "customer_ledger"("customer_id", "due_date");
CREATE INDEX "sales_customer_id_occurred_at_idx" ON "sales"("customer_id", "occurred_at");
ALTER TABLE "sales" ADD CONSTRAINT "sales_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "sales" ADD CONSTRAINT "sales_vehicle_id_fkey" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "customers" ADD CONSTRAINT "customers_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "vehicles" ADD CONSTRAINT "vehicles_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "customer_receipts" ADD CONSTRAINT "customer_receipts_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "customer_receipts" ADD CONSTRAINT "customer_receipts_station_id_fkey" FOREIGN KEY ("station_id") REFERENCES "stations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "customer_receipts" ADD CONSTRAINT "customer_receipts_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "customer_receipts" ADD CONSTRAINT "customer_receipts_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "customer_ledger" ADD CONSTRAINT "customer_ledger_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "customer_ledger" ADD CONSTRAINT "customer_ledger_station_id_fkey" FOREIGN KEY ("station_id") REFERENCES "stations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "customer_ledger" ADD CONSTRAINT "customer_ledger_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "customer_ledger" ADD CONSTRAINT "customer_ledger_sale_id_fkey" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "customer_ledger" ADD CONSTRAINT "customer_ledger_receipt_id_fkey" FOREIGN KEY ("receipt_id") REFERENCES "customer_receipts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "customer_ledger" ADD CONSTRAINT "customer_ledger_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
