import type { DensityReadingInput, InventoryAdjustmentInput, ReceiptInput, TankReadingInput } from '@fuelledger/shared';
import { Prisma } from '@prisma/client';
import { AppError } from '../../lib/errors.js';
import { prisma } from '../../lib/prisma.js';
import { postJournal } from '../accounting/service.js';

const tankInclude = { product: { select: { id: true, name: true, code: true, unit: true, category: true } }, physicalReadings: { take: 1, orderBy: { recordedAt: 'desc' as const } }, densityReadings: { take: 1, orderBy: { recordedAt: 'desc' as const } } } as const;
export async function bootstrap(organizationId: string,stationIds?:string[]) {
  const [stations, products, ledger, receipts] = await Promise.all([
    prisma.station.findMany({ where: { organizationId, active: true,...(stationIds?{id:{in:stationIds}}:{}) }, include: { configurations: { where: { active: true }, take: 1, include: { tanks: { where: { status: 'ACTIVE' }, include: tankInclude } } } } }),
    prisma.product.findMany({ where: { organizationId, active: true, inventoryTracked: true }, select: { id: true, name: true, code: true, unit: true, tankLinked: true } }),
    prisma.inventoryLedger.findMany({ where: { organizationId,...(stationIds?{stationId:{in:stationIds}}:{}) }, orderBy: { occurredAt: 'desc' }, take: 80, include: { product: { select: { name: true, code: true, unit: true } }, station: { select: { name: true, code: true } }, tank: { select: { code: true } } } }),
    prisma.purchaseReceipt.findMany({ where: { organizationId,...(stationIds?{stationId:{in:stationIds}}:{}) }, orderBy: { receivedAt: 'desc' }, take: 20, include: { station: { select: { name: true } }, lines: { include: { product: { select: { name: true, code: true, unit: true } }, tank: { select: { code: true } } } } } }),
  ]);
  const ledgerByTank = group(ledger.filter(entry => entry.tankId), entry => entry.tankId!); const ledgerByStationProduct = group(ledger.filter(entry => !entry.tankId), entry => `${entry.stationId}:${entry.productId}`);
  const tanks = stations.flatMap(station => station.configurations[0]?.tanks.map(tank => reconciliation({ station, tank, entries: ledgerByTank.get(tank.id) ?? [] })) ?? []);
  const untanked = stations.flatMap(station => products.filter(product => !product.tankLinked).map(product => reconciliation({ station, product, entries: ledgerByStationProduct.get(`${station.id}:${product.id}`) ?? [] }))).filter(item => item.opening || item.receipts || item.sales || item.adjustments || item.physicalStock !== null);
  return { stations, products, tanks, untanked, ledger, receipts };
}
function reconciliation({ station, tank, product, entries }: { station?: { id: string; name: string; code: string }; tank?: { id: string; code: string; openingStock: Prisma.Decimal; product: { id: string; name: string; code: string; unit: string; category: string }; physicalReadings: Array<{ physicalStock: Prisma.Decimal; dipReading: Prisma.Decimal | null; recordedAt: Date }>; densityReadings: Array<{ density: Prisma.Decimal; recordedAt: Date }> }; product?: { id: string; name: string; code: string; unit: string }; entries: Array<{ type: string; quantityDelta: Prisma.Decimal }> }) {
  const item = tank?.product ?? product!; const opening = Number(tank?.openingStock ?? 0); const receipts = sum(entries.filter(entry => entry.type === 'RECEIPT')); const sales = Math.abs(sum(entries.filter(entry => entry.type === 'SALE'))); const adjustments = sum(entries.filter(entry => entry.type === 'ADJUSTMENT')); const bookStock = opening + receipts - sales + adjustments; const reading = tank?.physicalReadings[0]; const densityReading = tank?.densityReadings[0]; const physicalStock = reading ? Number(reading.physicalStock) : null; return { station, tank: tank ? { id: tank.id, code: tank.code } : null, product: item, opening, receipts, sales, adjustments, bookStock, physicalStock, variance: physicalStock === null ? null : physicalStock - bookStock, dipReading: reading?.dipReading ? Number(reading.dipReading) : null, readAt: reading?.recordedAt ?? null, density: densityReading ? Number(densityReading.density) : null, densityRecordedAt: densityReading?.recordedAt ?? null };
}
const sum = (entries: Array<{ quantityDelta: Prisma.Decimal }>) => entries.reduce((total, entry) => total + Number(entry.quantityDelta), 0);
const group = <T>(values: T[], key: (value: T) => string) => values.reduce((map, value) => { const id = key(value); map.set(id, [...(map.get(id) ?? []), value]); return map; }, new Map<string, T[]>());
export async function receive(organizationId: string, userId: string, input: ReceiptInput) {
  const station = await prisma.station.findFirst({ where: { id: input.stationId, organizationId, active: true } }); if (!station) throw new AppError(404, 'STATION_NOT_FOUND', 'Choose an active station.');
  const products = await prisma.product.findMany({ where: { organizationId, id: { in: input.lines.map(line => line.productId) }, active: true, inventoryTracked: true } }); if (products.length !== new Set(input.lines.map(line => line.productId)).size) throw new AppError(400, 'PRODUCT_NOT_INVENTORIED', 'Every receipt line must use an active inventory product.');
  return prisma.$transaction(async tx => { const receipt = await tx.purchaseReceipt.create({ data: { organizationId, stationId: station.id, supplierName: input.supplierName, referenceNo: input.referenceNo || null, receivedAt: input.receivedAt ? new Date(input.receivedAt) : new Date(), notes: input.notes || null, createdById: userId } }); for (const line of input.lines) { const product = products.find(item => item.id === line.productId)!; const tank = line.tankId ? await tx.tank.findFirst({ where: { id: line.tankId, productId: product.id, configuration: { stationId: station.id, active: true }, status: 'ACTIVE' } }) : null; if (line.tankId && !tank) throw new AppError(400, 'TANK_MAPPING_INVALID', 'The selected tank must be active at this station and hold this product.'); if (product.tankLinked && !tank) throw new AppError(400, 'TANK_REQUIRED', `${product.name} must be received into its configured tank.`); const receiptLine = await tx.receiptLine.create({ data: { receiptId: receipt.id, productId: product.id, tankId: tank?.id ?? null, quantity: new Prisma.Decimal(line.quantity), unitCost: new Prisma.Decimal(line.unitCost) } }); await tx.inventoryLedger.create({ data: { organizationId, stationId: station.id, productId: product.id, tankId: tank?.id ?? null, type: 'RECEIPT', quantityDelta: new Prisma.Decimal(line.quantity), unitCost: new Prisma.Decimal(line.unitCost), receiptLineId: receiptLine.id, occurredAt: receipt.receivedAt, createdById: userId } }); } const total=input.lines.reduce((sum,line)=>sum+line.quantity*line.unitCost,0);await postJournal(tx,{organizationId,stationId:station.id,createdById:userId,journalDate:receipt.receivedAt,reference:`GRN-${receipt.id.slice(-8)}`,description:`Goods receipt from ${input.supplierName}`,sourceType:'PURCHASE_RECEIPT',sourceId:receipt.id,lines:[{account:'1200',debit:total},{account:'2000',credit:total}]});return receipt; });
}
export async function adjust(organizationId: string, userId: string, input: InventoryAdjustmentInput) {
  const product = await prisma.product.findFirst({ where: { id: input.productId, organizationId, active: true, inventoryTracked: true } }); if (!product) throw new AppError(404, 'PRODUCT_NOT_INVENTORIED', 'Choose an active inventory product.'); const tank = input.tankId ? await prisma.tank.findFirst({ where: { id: input.tankId, productId: product.id, configuration: { stationId: input.stationId, station: { organizationId } }, status: 'ACTIVE' } }) : null; if (input.tankId && !tank) throw new AppError(400, 'TANK_MAPPING_INVALID', 'The selected tank is not valid for this product and station.'); if (product.tankLinked && !tank) throw new AppError(400, 'TANK_REQUIRED', `${product.name} needs a tank adjustment.`); return prisma.$transaction(async tx=>{const entry=await tx.inventoryLedger.create({ data: { organizationId, stationId: input.stationId, productId: product.id, tankId: tank?.id ?? null, type: 'ADJUSTMENT', quantityDelta: new Prisma.Decimal(input.quantityDelta), note: input.notes, createdById: userId } });const amount=new Prisma.Decimal(Math.abs(input.quantityDelta)).mul(product.purchasePrice);await postJournal(tx,{organizationId,stationId:input.stationId,createdById:userId,journalDate:entry.occurredAt,reference:`ADJ-${entry.id.slice(-8)}`,description:`Inventory adjustment: ${product.name}`,sourceType:'INVENTORY_ADJUSTMENT',sourceId:entry.id,lines:input.quantityDelta>0?[{account:'1200',debit:amount},{account:'5100',credit:amount}]:[{account:'5100',debit:amount},{account:'1200',credit:amount}]});return entry;});
}
export async function recordTankReading(organizationId: string, userId: string, input: TankReadingInput) { const tank = await prisma.tank.findFirst({ where: { id: input.tankId, configuration: { stationId: input.stationId, station: { organizationId } }, status: 'ACTIVE' } }); if (!tank) throw new AppError(400, 'TANK_NOT_FOUND', 'Choose an active tank at this station.'); return prisma.tankReading.create({ data: { organizationId, stationId: input.stationId, tankId: tank.id, physicalStock: new Prisma.Decimal(input.physicalStock), dipReading: input.dipReading === null || input.dipReading === undefined ? null : new Prisma.Decimal(input.dipReading), notes: input.notes || null, recordedById: userId } }); }
export async function recordDensity(organizationId: string, userId: string, input: DensityReadingInput) { const tank = await prisma.tank.findFirst({ where: { id: input.tankId, configuration: { stationId: input.stationId, station: { organizationId } }, status: 'ACTIVE', product: { category: 'FUEL' } } }); if (!tank) throw new AppError(400, 'FUEL_TANK_NOT_FOUND', 'Choose an active petrol or diesel tank at this station.'); return prisma.tankDensityReading.create({ data: { organizationId, stationId: input.stationId, tankId: tank.id, density: new Prisma.Decimal(input.density), recordedById: userId } }); }
