import { useEffect, useMemo, useState } from 'react';
import { BookOpenCheck, CheckCircle2, ChevronDown, ChevronUp, ClipboardList, Landmark, ReceiptIndianRupee, Scale } from 'lucide-react';
import { api, ApiRequestError, type AccountingBootstrap } from '../lib/api';
import { useStation } from '../components/StationProvider';

const money = (value: number | string) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(Number(value));
const dateOnly = (value:string) => new Date(value).toLocaleDateString('en-IN', { day:'numeric', month:'short', year:'numeric', timeZone:'UTC' });
export const accountBalanceLabel=(account:{type:string;balance:number})=>{if(Math.abs(account.balance)<.01)return{amount:money(0),side:'Settled'};const normalCredit=account.type==='LIABILITY'||account.type==='REVENUE';const isNormal=account.balance>0;return{amount:money(Math.abs(account.balance)),side:(normalCredit===isNormal?'Credit':'Debit')+' balance'};};

export function AccountingPage() {
  const { selectedStationId } = useStation();
  const [data, setData] = useState<AccountingBootstrap | null>(null);
  const [open, setOpen] = useState('');
  const [error, setError] = useState('');
  const load=()=>{setData(null);setError('');void api.accountingBootstrap(selectedStationId || undefined).then(setData).catch(item=>setError(item instanceof ApiRequestError?item.message:'Unable to load accounting.'));};
  useEffect(load, [selectedStationId]);
  const groups = useMemo(() => data ? ['ASSET', 'LIABILITY', 'REVENUE', 'EXPENSE'].map(type => ({ type, accounts: data.accounts.filter(account => account.type === type) })).filter(group => group.accounts.length) : [], [data]);
  if(!data)return <main className="page">{error?<div className="fatal"><div><h2>Accounting did not load</h2><p>{error}</p><button onClick={load}>Try again</button></div></div>:<div className="loading"><span/><p>Preparing the accounting ledger…</p></div>}</main>;
  const balanced = Math.abs(data.trial.debit - data.trial.credit) < .01;
  const openPayables=data.payables.filter(invoice=>invoice.outstanding>.01),payableTotal=openPayables.reduce((sum,invoice)=>sum+invoice.outstanding,0),overdueTotal=openPayables.filter(invoice=>invoice.overdue).reduce((sum,invoice)=>sum+invoice.outstanding,0);
  return <main className="page accounting-page">
    <div className="page-heading"><div><span className="eyebrow">Accounting engine</span><h1>Every operational fact has a balanced trail</h1><p>Journals are created automatically and remain linked to the original transaction.</p></div><span className={balanced ? 'accounting-proof' : 'accounting-proof problem'}>{balanced ? <CheckCircle2 size={16}/> : <Scale size={16}/>}<span><b>{balanced ? 'Books balanced' : 'Needs review'}</b><small>Dr {money(data.trial.debit)} · Cr {money(data.trial.credit)}</small></span></span></div>
    <section className="accounting-hero"><div><span><Landmark/></span><div><small>Open supplier balance</small><b>{money(payableTotal)}</b><p>{openPayables.length} invoice{openPayables.length===1?'':'s'} still awaiting payment.</p></div></div><div><span><ReceiptIndianRupee/></span><div><small>Overdue supplier balance</small><b>{money(overdueTotal)}</b><p>Calculated from each invoice date and the supplier's payment terms.</p></div></div><div><span><BookOpenCheck/></span><div><small>Posted journals</small><b>{data.journals.length}</b><p>Operational entries posted to the general ledger.</p></div></div></section>
    <section className="payables-section"><div className="history-head"><div><span className="eyebrow">Supplier payables</span><h2>Invoice dates and payment position</h2><p>Due dates follow the invoice date and the supplier's configured credit period.</p></div><ReceiptIndianRupee size={18}/></div><div className="payables-head"><span>Invoice</span><span>Invoice date</span><span>Due date</span><span>Invoice amount</span><span>Paid</span><span>Outstanding</span></div>{data.payables.map(invoice=><div className="payable-row" key={invoice.id}><span><b>{invoice.supplier.name}</b><small>{invoice.invoiceNumber} · {invoice.station.name}</small></span><span data-label="Invoice date">{dateOnly(invoice.invoiceDate)}</span><span data-label="Due date">{dateOnly(invoice.dueDate)}<small className={invoice.overdue?'payable-status overdue':'payable-status'}>{invoice.outstanding<.01?'Paid':invoice.overdue?'Overdue':'Open'}</small></span><span data-label="Invoice amount">{money(invoice.total)}</span><span data-label="Paid">{money(invoice.paid)}</span><strong data-label="Outstanding">{money(invoice.outstanding)}</strong></div>)}{!data.payables.length&&<p className="history-empty">Purchase invoices will appear here with their invoice and due dates.</p>}</section>
    <section className="accounting-layout"><div className="trial-section"><div className="history-head"><div><span className="eyebrow">Trial balance</span><h2>Account balances</h2><p>Balances are labelled Debit or Credit—never shown as confusing negative amounts.</p></div><Scale size={18}/></div>{groups.map(group => <div className="account-group" key={group.type}><h3>{group.type.toLowerCase()}</h3><div className="account-head"><span>Account</span><span>Movement</span><span>Closing balance</span></div>{group.accounts.map(account => {const display=accountBalanceLabel(account);return <div className="account-row" key={account.id}><span><b>{account.code}</b><strong>{account.name}</strong></span><span><small>Debit</small>{money(account.debit)}<small>Credit</small>{money(account.credit)}</span><span><b>{display.amount}</b><small>{display.side}</small></span></div>;})}</div>)}</div>
      <div className="journal-section"><div className="history-head"><div><span className="eyebrow">General ledger</span><h2>Latest postings</h2><p>The accounting date matches the operational document date.</p></div><ClipboardList size={18}/></div>{data.journals.map(journal => { const expanded = open === journal.id; return <article key={journal.id}><button onClick={() => setOpen(expanded ? '' : journal.id)}><span className="journal-mark"><BookOpenCheck size={16}/></span><span><strong>{journal.description}</strong><small>{dateOnly(journal.journalDate)} · {journal.reference} · {journal.sourceType.replaceAll('_', ' ')}</small></span>{expanded ? <ChevronUp size={16}/> : <ChevronDown size={16}/>}</button>{expanded && <div className="journal-lines">{journal.lines.map(line => <div key={line.id}><span><b>{line.account.code}</b> {line.account.name}</span><span>{Number(line.debit) ? `Dr ${money(line.debit)}` : `Cr ${money(line.credit)}`}</span></div>)}</div>}</article>; })}{!data.journals.length && <p className="history-empty">New operational activity will post here automatically.</p>}</div>
    </section>
  </main>;
}
