import { render, screen } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { describe, expect, it, vi } from 'vitest';
import { DashboardPage } from './DashboardPage';

vi.mock('../lib/api',()=>({ApiRequestError:class extends Error{},api:{dashboardBootstrap:vi.fn().mockResolvedValue({asOf:'2026-09-01T12:00:00.000Z',today:{grossSales:5110,transactions:6,meteredVolume:35,purchases:3990,expenses:2600,receivables:1590,payables:2990,inventoryValue:96270,grossProfit:8,netProfit:-92},collections:[{key:'CASH',method:'CASH',transactions:2,amount:2570}],topProducts:[{key:'ms',product:'Motor Spirit',code:'MS',unit:'LITRE',quantity:35,revenue:3570}],trend:{days:[{date:'2026-09-01',amount:5110}],thisWeek:5110,previousWeek:0,weekChange:null},operations:{openShifts:0,pendingReconciliations:1,cashVariance:0},actions:[{id:'reconciliation',severity:'HIGH',title:'1 shift waiting for reconciliation',detail:'Review and lock the shift.',href:'/reconciliation'}],stationHealth:[{id:'one',name:'Station C',code:'ST-C',sales:5110,transactions:6,openShifts:0,pendingReconciliations:1,stockAlerts:0,status:'ATTENTION'}],tankStocks:[{id:'tank-1',code:'MS-1',product:'Motor Spirit',productCode:'MS',unit:'LITRE',station:{id:'one',name:'Station C',code:'ST-C'},bookStock:12500,workingCapacity:20000,fillPercent:62.5,sellingPrice:102,density:742.5,densityRecordedAt:'2026-09-01T05:00:00.000Z',physicalStock:12480,physicalReadingAt:'2026-09-01T12:00:00.000Z',status:'HEALTHY'}]})}}));
vi.mock('../components/StationProvider',()=>({useStation:()=>({selectedStationId:'',selectedStation:null})}));

describe('DashboardPage',()=>{it('surfaces owner metrics and priority actions',async()=>{render(<MemoryRouter><DashboardPage/></MemoryRouter>);expect(await screen.findByRole('heading',{name:'Your business, under control'})).toBeInTheDocument();expect(screen.getByText('1 shift waiting for reconciliation')).toBeInTheDocument();expect(screen.getByRole('heading',{name:'Live tank levels'})).toBeInTheDocument();expect(screen.getByRole('heading',{name:'MS Tank 1'})).toBeInTheDocument();expect(screen.getByText('742.5 kg/m³')).toBeInTheDocument();expect(screen.getByRole('heading',{name:'Fuel stations right now'})).toBeInTheDocument();});});
