import { cleanup, render, screen } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { DashboardPage } from './DashboardPage';

const {subscription,dailyBriefing}=vi.hoisted(()=>({subscription:vi.fn(),dailyBriefing:vi.fn()}));
vi.mock('../lib/api',()=>({ApiRequestError:class extends Error{},api:{subscription,dailyBriefing,dashboardBootstrap:vi.fn().mockResolvedValue({asOf:'2026-09-01T12:00:00.000Z',today:{grossSales:5110,transactions:6,meteredVolume:35,purchases:3990,expenses:2600,receivables:1590,payables:2990,inventoryValue:96270,grossProfit:8,netProfit:-92},collections:[{key:'CASH',method:'CASH',transactions:2,amount:2570}],topProducts:[{key:'ms',product:'Motor Spirit',code:'MS',unit:'LITRE',quantity:35,revenue:3570}],trend:{days:[{date:'2026-09-01',amount:5110}],thisWeek:5110,previousWeek:0,weekChange:null},operations:{openShifts:0,pendingReconciliations:1,cashVariance:0},actions:[{id:'reconciliation',severity:'HIGH',title:'1 shift waiting for reconciliation',detail:'Review and lock the shift.',href:'/reconciliation'}],stationHealth:[{id:'one',name:'Station C',code:'ST-C',sales:5110,transactions:6,openShifts:0,pendingReconciliations:1,stockAlerts:0,status:'ATTENTION'}],tankStocks:[{id:'tank-1',code:'MS-1',product:'Motor Spirit',productCode:'MS',unit:'LITRE',station:{id:'one',name:'Station C',code:'ST-C'},bookStock:12500,workingCapacity:20000,fillPercent:62.5,sellingPrice:102,density:742.5,densityRecordedAt:'2026-09-01T05:00:00.000Z',physicalStock:12480,physicalReadingAt:'2026-09-01T12:00:00.000Z',status:'HEALTHY'}]})}}));
vi.mock('../components/StationProvider',()=>({useStation:()=>({selectedStationId:'',selectedStation:null})}));
vi.mock('../components/AuthProvider',()=>({useAuth:()=>({user:{name:'Owner'}})}));
afterEach(()=>{cleanup();vi.clearAllMocks();});

describe('DashboardPage',()=>{
  it('keeps priority actions for a Core-only owner',async()=>{subscription.mockResolvedValue({intelligenceEnabledAt:null,intelligenceExpiresAt:null});render(<MemoryRouter><DashboardPage/></MemoryRouter>);expect(await screen.findByRole('heading',{name:'Your business, under control'})).toBeInTheDocument();expect(screen.getByText('1 shift waiting for reconciliation')).toBeInTheDocument();expect(screen.queryByRole('heading',{name:/fuel station needs attention/i})).not.toBeInTheDocument();expect(dailyBriefing).not.toHaveBeenCalled();expect(screen.getByRole('heading',{name:'Live tank levels'})).toBeInTheDocument();expect(screen.getByRole('heading',{name:'MS Tank 1'})).toBeInTheDocument();expect(screen.getByText('742.5 kg/m³')).toBeInTheDocument();expect(screen.getByRole('heading',{name:'Fuel stations right now'})).toBeInTheDocument();});
  it('replaces the action card with the verified Daily Brief for Core plus Intelligence',async()=>{subscription.mockResolvedValue({intelligenceEnabledAt:'2026-09-01T00:00:00.000Z',intelligenceExpiresAt:null});dailyBriefing.mockResolvedValue({date:'2026-09-01',calculatedAt:'2026-09-01T12:00:00.000Z',facts:[{id:'pending-reconciliation',category:'SHIFT',severity:'URGENT',label:'Shifts awaiting reconciliation',value:'1',context:'Collections await review.',evidenceLabel:'Reconciliation records',evidencePath:'/reconciliation'},{id:'sales-today',category:'SALES',severity:'POSITIVE',label:'Sales today',value:'₹5,110',context:'Compared with yesterday: +8.4%.',evidenceLabel:'Sales records',evidencePath:'/sales'}],narrative:{headline:'Your fuel station needs attention',summary:'Review the most important signals.',items:[{factId:'pending-reconciliation',explanation:'Expected and actual collections have not yet been approved.',action:'Review reconciliation records.'},{factId:'sales-today',explanation:'Sales are above the previous comparison.',action:'Keep monitoring this signal.'}]},narrativeMode:'DETERMINISTIC',model:null});render(<MemoryRouter><DashboardPage/></MemoryRouter>);expect(await screen.findByRole('heading',{name:'Your fuel station needs attention'})).toBeInTheDocument();expect(screen.getByText('FuelNerve Intelligence')).toBeInTheDocument();expect(screen.getByText('Daily brief')).toBeInTheDocument();expect(screen.getByRole('link',{name:/Shifts awaiting reconciliation/})).toHaveAttribute('href','/reconciliation');expect(screen.getByRole('link',{name:/Open daily brief/})).toHaveAttribute('href','/insights');expect(screen.queryByRole('heading',{name:'What needs action'})).not.toBeInTheDocument();});
  it('keeps the Core dashboard usable when plan status is unavailable',async()=>{subscription.mockRejectedValue(new Error('offline'));render(<MemoryRouter><DashboardPage/></MemoryRouter>);expect(await screen.findByRole('heading',{name:'What needs action'})).toBeInTheDocument();expect(screen.getByText('1 shift waiting for reconciliation')).toBeInTheDocument();});
});
