import { useEffect, useState } from 'react';
import { Car, Pencil, ReceiptText, Trash2, X } from 'lucide-react';
import { api, ApiRequestError, type Customer } from '../lib/api';

const money=(value:number|string)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(value));
export function EditableCustomerDetail({customer,onReceipt,onVehicle,onChanged}:{customer:Customer;onReceipt:()=>void;onVehicle:()=>void;onChanged:()=>Promise<void>}){
 const [editing,setEditing]=useState(false),[saving,setSaving]=useState(false),[confirmDelete,setConfirmDelete]=useState(false),[error,setError]=useState('');
 const makeForm=()=>({name:customer.name,type:customer.type,phone:customer.phone??'',email:customer.email??'',taxId:customer.taxId??'',billingAddress:customer.billingAddress??'',creditLimit:Number(customer.creditLimit),creditDays:customer.creditDays,active:true});
 const [form,setForm]=useState(makeForm);
 useEffect(()=>setForm(makeForm()),[customer]);
 async function save(){setSaving(true);setError('');try{await api.updateCustomer(customer.id,form);setEditing(false);await onChanged();}catch(e){setError(e instanceof ApiRequestError?e.message:'Unable to update this customer.');}finally{setSaving(false);}}
 async function remove(){setSaving(true);setError('');try{await api.removeCustomer(customer.id);setEditing(false);await onChanged();}catch(e){setError(e instanceof ApiRequestError?e.message:'Unable to delete this customer.');}finally{setSaving(false);}}
 const age=customer.ageing;
 return <section className="customer-detail"><header><div><span className="eyebrow">{customer.type==='FLEET'?'Fleet account':'Credit customer'}</span><h2>{customer.name}</h2><p>{customer.code} · {customer.phone||'No phone added'} · {customer.creditDays} day terms</p></div><div className="customer-actions"><button className="secondary" onClick={()=>{setConfirmDelete(false);setEditing(true);}}><Pencil size={15}/> Edit</button><button className="secondary" onClick={onVehicle}><Car size={15}/> Add vehicle</button><button className="primary small" onClick={onReceipt}><ReceiptText size={15}/> Receive payment</button></div></header>
 <div className="credit-strip"><div><span>Outstanding</span><b>{money(customer.outstanding)}</b></div><div><span>Credit limit</span><b>{money(customer.creditLimit)}</b></div><div><span>Available</span><b>{money(customer.availableCredit)}</b></div><i><span style={{width:`${Math.min(100,Math.max(0,customer.outstanding/Math.max(1,Number(customer.creditLimit))*100))}%`}}/></i></div>
 <div className="ageing-card"><h3>Ageing at a glance</h3>{[['Not yet due',age.current],['1–30 days',age.days1to30],['31–60 days',age.days31to60],['61–90 days',age.days61to90],['90+ days',age.days90plus]].map(([label,value])=><div key={String(label)}><span>{label}</span><b className={Number(value)>0&&label!=='Not yet due'?'overdue':''}>{money(Number(value))}</b></div>)}</div>
 {customer.vehicles.length>0&&<div className="vehicle-chips"><Car size={15}/>{customer.vehicles.map(x=><span key={x.id}>{x.number}{x.label?` · ${x.label}`:''}</span>)}</div>}
 <div className="customer-ledger"><div className="history-head"><div><span className="eyebrow">Customer ledger</span><h2>Account activity</h2></div><span>{customer.ledger.length} entries</span></div>{customer.ledger.length?customer.ledger.map(entry=><article key={entry.id}><span className={`ledger-type ${entry.type.toLowerCase()}`}>{entry.type}</span><div><strong>{entry.description}</strong><small>{new Date(entry.occurredAt).toLocaleDateString('en-IN',{dateStyle:'medium'})} · {entry.station.name}{entry.sale?` · ${entry.sale.product.category}`:''}</small></div><b className={Number(entry.amount)>0?'debit':'credit'}>{Number(entry.amount)>0?'+':'−'}{money(Math.abs(Number(entry.amount)))}</b></article>):<p className="history-empty">No credit sales or receipts yet.</p>}</div>
 {editing&&<div className="product-modal"><section className="product-editor customer-modal"><button className="modal-close" onClick={()=>setEditing(false)}><X size={17}/></button><span className="eyebrow">{customer.code}</span><h2>Edit customer</h2>{error&&<div className="form-error">{error}</div>}<div className="form-grid"><label className="field"><span>Customer name</span><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="field"><span>Mobile number</span><input inputMode="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="field"><span>Credit limit (₹)</span><input type="number" min="0" value={form.creditLimit} onChange={e=>setForm({...form,creditLimit:Number(e.target.value)})}/></label><label className="field"><span>Payment due in days</span><input type="number" min="0" max="365" value={form.creditDays} onChange={e=>setForm({...form,creditDays:Number(e.target.value)})}/></label></div><label className="field"><span>Billing address (optional)</span><input value={form.billingAddress} onChange={e=>setForm({...form,billingAddress:e.target.value})}/></label>{confirmDelete&&<div className="form-error">{Math.abs(customer.outstanding)>=0.005?'This account has a balance. Settle it before deleting the customer.':'Delete this customer from active accounts? Past sales and payments will remain safely recorded.'}</div>}<div className="editor-footer"><button className="secondary danger" disabled={saving||(confirmDelete&&Math.abs(customer.outstanding)>=0.005)} onClick={()=>confirmDelete?void remove():setConfirmDelete(true)}><Trash2 size={15}/>{confirmDelete?'Confirm delete':'Delete customer'}</button><button className="secondary" onClick={()=>setEditing(false)}>Cancel</button><button className="primary small" disabled={saving||!form.name.trim()} onClick={()=>void save()}>{saving?'Saving…':'Save changes'}</button></div></section></div>}</section>;
}
