import { fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { describe, expect, it, vi } from "vitest";
import { IntelligenceAgentsPage } from "./IntelligenceAgentsPage";

vi.mock("../components/StationProvider", () => ({ useStation: () => ({ selectedStationId: "station-a", selectedStation: { name: "Station A" } }) }));
vi.mock("../components/AuthProvider", () => ({ useAuth: () => ({ user: { name: "Owner" } }) }));
const { stockAgent, investigateFinding, investigationFollowUp } = vi.hoisted(() => {
  const agent = { agentKey: "inventory-watch", name: "Stock Agent", purpose: "Tanks, readings, receipts and movement", icon: "stock" as const };
  return { stockAgent: agent, investigateFinding: vi.fn().mockResolvedValue({ investigationId: "investigation-1", agent, subject: "Stock is empty", headline: "Investigation: Stock is empty", summary: "The recorded balance shows no available stock at this position.", status: "READ_ONLY", generatedAt: new Date().toISOString(), recordsReviewed: 2, snapshotHash: "snapshot-hash", narrativeMode: "DETERMINISTIC", observations: [{ title: "Available balance", detail: "The current recorded balance is empty.", value: "0", factIds: ["fact-1"], evidenceIds: ["evidence-1"] }, { title: "Latest reading", detail: "The latest tank reading supports the current position.", factIds: ["fact-2"], evidenceIds: ["evidence-2"] }, { title: "Recent receipts", detail: "No later receipt was found in the records checked.", factIds: ["fact-3"], evidenceIds: ["evidence-2"] }, { title: "Hidden fourth observation", detail: "This should not appear in the default briefing.", factIds: [], evidenceIds: [] }], timeline: [{ title: "Reading recorded", detail: "The tank reading was saved.", occurredAt: new Date().toISOString(), factIds: [], evidenceIds: ["evidence-1"] }, { title: "Balance calculated", detail: "FuelNerve calculated the position.", occurredAt: new Date().toISOString(), factIds: [], evidenceIds: ["evidence-2"] }], possibleExplanations: [], unknowns: [{ title: "Delivery timing", detail: "I could not confirm whether an unrecorded delivery is expected.", factIds: [], evidenceIds: ["evidence-2"] }], nextChecks: [{ label: "Open inventory", detail: "Check the tank timeline and any planned receipt.", resolverPath: "/inventory", evidenceIds: ["evidence-1"] }], evidence: [{ evidenceId: "evidence-1", evidenceType: "inventory-position", label: "Current stock position", observedAt: new Date().toISOString(), resolverPath: "/inventory" }, { evidenceId: "evidence-2", evidenceType: "tank-reading", label: "Latest tank reading", observedAt: new Date().toISOString(), resolverPath: "/inventory" }] }), investigationFollowUp: vi.fn().mockResolvedValue({ investigationId: "investigation-1", agent, prompt: "WHY_HIGHEST_PRIORITY", question: "Why is this the highest priority?", status: "READ_ONLY", snapshotHash: "snapshot-hash", supported: true, answer: "I put DEF T-1 first because the recorded balance is empty.", citations: [{ evidenceId: "evidence-1", label: "Current stock position", resolverPath: "/inventory" }] }) };
});
vi.mock("../lib/api", () => ({ ApiRequestError: class extends Error {}, api: { askFuelNerve: vi.fn(), investigateFinding, investigationFollowUp, nerveAgents: vi.fn().mockResolvedValue({ mode: "READ_ONLY", sourceMode: "SHADOW", generatedAt: new Date().toISOString(), stale: false, safety: { evidenceVerified: true, crossTenantDenied: true, crossStationDenied: true, offlineSafe: true, proposalsEnabled: false, actionsEnabled: false }, summary: { agents: 2, findings: 4, urgent: 1 }, agents: [{ ...stockAgent, runId: "run-1", status: "NEEDS_ATTENTION", lastCompletedAt: new Date().toISOString(), findings: [{ findingId: "finding-1", type: "INVENTORY_EMPTY", severity: "URGENT", title: "Stock is empty", agent: stockAgent, whyItMatters: "No stock remains.", recommendedNextStep: "Review receipts.", displayValue: 0, calculatedAt: new Date().toISOString(), evidence: [{ label: "Inventory records", resolverPath: "/inventory" }] }, ...[-18, -11, -4].map((displayValue, index) => ({ findingId: `variance-${index}`, type: "PHYSICAL_BOOK_VARIANCE", severity: "ATTENTION" as const, title: "Physical and book stock differ", agent: stockAgent, whyItMatters: "The values differ.", recommendedNextStep: "Compare the reading with stock movements.", displayValue, calculatedAt: new Date().toISOString(), evidence: [{ label: "Inventory records", resolverPath: "/inventory" }] }))] }, { agentKey: "reconciliation-review", name: "Shift Agent", purpose: "Shifts, collections and handovers", icon: "shift", runId: "run-2", status: "ALL_CLEAR", lastCompletedAt: new Date().toISOString(), findings: [] }] }) } }));

function renderAgent(agentKey = "inventory-watch") {
  return render(<MemoryRouter initialEntries={[`/insights/${agentKey}`]}><Routes><Route path="/insights/:agentKey" element={<IntelligenceAgentsPage/>}/></Routes></MemoryRouter>);
}

describe("IntelligenceAgentsPage", () => { it("shows all six specialists as links without repeating their findings", async () => { render(<MemoryRouter><IntelligenceAgentsPage/></MemoryRouter>); expect(await screen.findByRole("heading", { name: "Nerve Intelligence" })).toBeInTheDocument(); expect(screen.getByRole("region", { name: "Nerve Intelligence specialists for Station A" })).toBeInTheDocument(); expect(screen.getByText("Station A", { selector: "strong" })).toBeInTheDocument(); expect(screen.getByRole("link", { name: /Stock Agent/ })).toHaveAttribute("href", "/insights/inventory-watch"); expect(screen.getByRole("link", { name: /Credit Agent/ })).toHaveAttribute("href", "/insights/credit-watch"); expect(screen.getByText("Needs your attention")).toBeInTheDocument(); expect(screen.getByText("Shift Agent")).toBeInTheDocument(); expect(screen.getByText("All clear")).toBeInTheDocument(); for (const name of ["Credit Agent", "Purchase Agent", "Profit Agent", "Owner Assistant"]) expect(screen.getByText(name)).toBeInTheDocument(); expect(screen.getAllByText("Awaiting first review")).toHaveLength(4); expect(screen.queryByRole("heading", { name: "A stock position is empty" })).not.toBeInTheDocument(); });

  it("opens a concise agent briefing with audit details collapsed", async () => { renderAgent(); fireEvent.click((await screen.findAllByRole("button", { name: "Let Stock Agent investigate" }))[0]!); const dialog = await screen.findByRole("dialog"); expect(dialog).toHaveAttribute("aria-modal", "true"); expect(dialog).toHaveAttribute("aria-labelledby", "investigation-title"); expect(within(dialog).getAllByText("Stock Agent").length).toBeGreaterThan(0); expect(within(dialog).getByText("Agent briefing")).toBeInTheDocument(); expect(within(dialog).getByRole("heading", { name: "Stock is empty" })).toBeInTheDocument(); expect(within(dialog).getByText("My assessment")).toBeInTheDocument(); expect(within(dialog).getByRole("heading", { name: "Why I think this" })).toBeInTheDocument(); expect(within(dialog).getByRole("heading", { name: "What I could not confirm" })).toBeInTheDocument(); expect(within(dialog).getByRole("heading", { name: "What to check next" })).toBeInTheDocument(); expect(within(dialog).getByRole("link", { name: /Open inventory/ })).toHaveAttribute("href", "/inventory"); expect(within(dialog).queryByText("Hidden fourth observation")).not.toBeInTheDocument(); const records = within(dialog).getByText("Records I checked").closest("details"); const timeline = within(dialog).getByText("Timeline").closest("details"); const technical = within(dialog).getByText("How I reached this").closest("details"); expect(records).not.toHaveAttribute("open"); expect(timeline).not.toHaveAttribute("open"); expect(technical).not.toHaveAttribute("open"); expect(within(dialog).queryByText(/evidence-backed|supported observation|possible connections|record sources reviewed|deterministic investigation/i)).not.toBeInTheDocument(); });

  it("keeps follow-ups inside the current agent, station, and saved briefing", async () => { investigationFollowUp.mockClear(); renderAgent(); fireEvent.click((await screen.findAllByRole("button", { name: "Let Stock Agent investigate" }))[0]!); const dialog = await screen.findByRole("dialog"); expect(within(dialog).getByRole("region", { name: "Questions for Stock Agent" })).toBeInTheDocument(); expect(within(dialog).queryByRole("textbox")).not.toBeInTheDocument(); fireEvent.click(within(dialog).getByRole("button", { name: "Why is this the highest priority?" })); await waitFor(() => expect(investigationFollowUp).toHaveBeenCalledWith("investigation-1", { stationId: "station-a", prompt: "WHY_HIGHEST_PRIORITY" })); expect(await within(dialog).findByText("I put DEF T-1 first because the recorded balance is empty.")).toBeInTheDocument(); const supportingRecords = within(dialog).getByRole("navigation", { name: "Supporting records" }); expect(within(supportingRecords).getByRole("link", { name: /Current stock position/ })).toHaveAttribute("href", "/inventory"); expect(within(dialog).getByText("Nerve Intelligence can review and explain. Only you can make changes.")).toBeInTheDocument(); expect(within(dialog).queryByRole("button", { name: /approve|execute|send|propose/i })).not.toBeInTheDocument(); });

  it("traps keyboard focus and returns it to the finding when closed", async () => { renderAgent(); const trigger = (await screen.findAllByRole("button", { name: "Let Stock Agent investigate" }))[0]!; trigger.focus(); fireEvent.click(trigger); const dialog = await screen.findByRole("dialog"); const close = within(dialog).getByRole("button", { name: "Close agent briefing" }); await waitFor(() => expect(close).toHaveFocus()); fireEvent.keyDown(dialog, { key: "Escape" }); await waitFor(() => expect(screen.queryByRole("dialog")).not.toBeInTheDocument()); await waitFor(() => expect(trigger).toHaveFocus()); });
});
