import { useEffect, useState } from 'react';
import { BellRing, Check, CircleAlert, Clock3, MessageCircleMore, Send, ShieldCheck, TriangleAlert } from 'lucide-react';
import { useAuth } from '../components/AuthProvider';
import { ApiRequestError, api, type NotificationDelivery, type NotificationSettings } from '../lib/api';

const defaults: NotificationSettings = { whatsappNumber: null, whatsappOptedIn: false, densityMissingEnabled: true, lowStockEnabled: true, shiftVarianceEnabled: true, unclosedShiftEnabled: true, dailySummaryEnabled: true, overdueCustomerEnabled: true, lowStockPercent: 20, varianceThreshold: 500, dailySummaryHour: 20, providerReady: false };
const options = [
  ['densityMissingEnabled', 'Missing morning density', 'One reminder when a fuel tank density entry is missing.', Clock3],
  ['lowStockEnabled', 'Low tank stock', 'An alert when a tank falls below your chosen stock level.', TriangleAlert],
  ['shiftVarianceEnabled', 'Shift cash variance', 'Sent when a reconciled shift crosses your variance limit.', CircleAlert],
  ['unclosedShiftEnabled', 'Shift still open', 'A late-evening reminder for shifts that have not been closed.', Clock3],
  ['dailySummaryEnabled', 'Daily business summary', 'Sales, fuel sold, expenses and net result at your selected time.', BellRing],
  ['overdueCustomerEnabled', 'Overdue customer payments', 'A daily alert when customer credit has become overdue.', CircleAlert],
] as const;
const deliveryLabel: Record<string, string> = { DENSITY_MISSING: 'Missing density', LOW_STOCK: 'Low stock', SHIFT_VARIANCE: 'Shift variance', SHIFT_OPEN: 'Open shift', DAILY_SUMMARY: 'Daily summary', OVERDUE_CUSTOMER: 'Overdue customers', SYSTEM_TEST: 'Test message' };

export function NotificationsPage() {
  const { user } = useAuth();
  const [settings, setSettings] = useState(defaults); const [deliveries, setDeliveries] = useState<NotificationDelivery[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [testing, setTesting] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const load = async () => { setLoading(true); try { const result = await api.notificationSettings(); setSettings(result.settings); setDeliveries(result.deliveries); } catch (caught) { setError(caught instanceof ApiRequestError ? caught.message : 'Unable to load WhatsApp notification settings.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  if (user?.role !== 'OWNER') return <main className="page"><div className="form-error">Only the owner can manage WhatsApp notifications.</div></main>;
  const save = async () => { setSaving(true); setError(''); setMessage(''); try { const result = await api.updateNotificationSettings({ ...settings, whatsappNumber: settings.whatsappNumber ?? '' }); setSettings(result.settings); setMessage('WhatsApp notification settings saved.'); } catch (caught) { setError(caught instanceof ApiRequestError ? caught.message : 'Unable to save notification settings.'); } finally { setSaving(false); } };
  const test = async () => { setTesting(true); setError(''); setMessage(''); try { const result = await api.testWhatsApp(); if (result.delivery.status === 'SENT') { setMessage('Test message sent to the owner’s WhatsApp number.'); await load(); } else setError(result.delivery.reason ?? 'The test message could not be sent.'); } catch (caught) { setError(caught instanceof ApiRequestError ? caught.message : 'Unable to send the WhatsApp test message.'); } finally { setTesting(false); } };
  return <main className="page notifications-page">
    <section className="notification-hero"><div><span className="eyebrow">Owner alerts</span><h1>Know what needs attention.</h1><p>FuelLedger sends only the business alerts you choose—never a stream of routine activity.</p></div><span><MessageCircleMore /></span></section>
    {error&&<div className="form-error">{error}</div>}{message&&<div className="success-banner">{message}</div>}
    {loading?<div className="loading-inline">Loading notification settings…</div>:<>
      <section className="notification-setup"><header><div><span className="notification-icon"><MessageCircleMore /></span><div><span className="eyebrow">WhatsApp delivery</span><h2>Owner’s WhatsApp number</h2><p>Use a number with country code, for example 918977506454.</p></div></div><span className={settings.providerReady?'notification-ready':'notification-pending'}>{settings.providerReady?<><Check /> Connected</>:<><TriangleAlert /> Setup needed</>}</span></header><div className="notification-number"><label><span>WhatsApp number</span><input inputMode="tel" placeholder="919876543210" value={settings.whatsappNumber??''} onChange={event=>setSettings({...settings,whatsappNumber:event.target.value.replace(/[^0-9+]/g,'')})}/></label><label className="notification-consent"><input type="checkbox" checked={settings.whatsappOptedIn} onChange={event=>setSettings({...settings,whatsappOptedIn:event.target.checked})}/><span><b>Owner has opted in to WhatsApp alerts</b><small>Only use a number that has agreed to receive FuelLedger notifications.</small></span></label><button className="secondary" disabled={!settings.providerReady||!settings.whatsappOptedIn||testing} onClick={()=>void test()}><Send size={16}/>{testing?'Sending…':'Send test message'}</button></div>{!settings.providerReady&&<p className="notification-help"><ShieldCheck size={16}/> Add the WhatsApp API credentials in Vercel to enable delivery. Your alert choices are still saved safely.</p>}</section>
      <section className="notification-layout"><article className="notification-rules"><header><span className="eyebrow">Choose your alerts</span><h2>Important notifications</h2><p>Every alert is sent at most once per relevant event or day to avoid duplicate messages.</p></header><div>{options.map(([key,title,detail,Icon])=><label className="notification-rule" key={key}><span><Icon /></span><div><b>{title}</b><small>{detail}</small></div><input type="checkbox" checked={settings[key]} onChange={event=>setSettings({...settings,[key]:event.target.checked})}/><i /></label>)}</div></article><aside className="notification-thresholds"><span className="eyebrow">Your limits</span><h2>When to alert you</h2><label><span>Low-stock level</span><div><input type="number" min="1" max="50" value={settings.lowStockPercent} onChange={event=>setSettings({...settings,lowStockPercent:Number(event.target.value)})}/><b>%</b></div><small>Alert when a tank reaches this percentage or lower.</small></label><label><span>Cash variance limit</span><div><b>₹</b><input type="number" min="0" value={settings.varianceThreshold} onChange={event=>setSettings({...settings,varianceThreshold:Number(event.target.value)})}/></div><small>Alert only when the absolute shift variance reaches this amount.</small></label><label><span>Daily summary time</span><select value={settings.dailySummaryHour} onChange={event=>setSettings({...settings,dailySummaryHour:Number(event.target.value)})}>{Array.from({length:24},(_,hour)=><option key={hour} value={hour}>{String(hour).padStart(2,'0')}:30 IST</option>)}</select><small>FuelLedger checks hourly and sends the summary in Indian Standard Time.</small></label><button className="primary small" disabled={saving} onClick={()=>void save()}>{saving?'Saving…':'Save notification settings'}</button></aside></section>
      <section className="notification-history"><header><div><span className="eyebrow">Delivery history</span><h2>Recent WhatsApp alerts</h2></div><span>{deliveries.length} recent</span></header>{deliveries.length?<div>{deliveries.map(delivery=><article key={delivery.id}><span className={delivery.status.toLowerCase()}>{delivery.status==='SENT'?<Check/>:<TriangleAlert/>}</span><div><b>{deliveryLabel[delivery.type]??delivery.type}</b><small>{delivery.station?.name??'All petrol pumps'} · {new Date(delivery.createdAt).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}</small><p>{delivery.message}</p>{delivery.errorMessage&&<em>{delivery.errorMessage}</em>}</div><strong>{delivery.status==='SENT'?'Sent':delivery.status==='FAILED'?'Failed':'Waiting'}</strong></article>)}</div>:<div className="notification-empty"><BellRing/><b>No WhatsApp alerts sent yet</b><small>Your delivery history will appear here after the first alert.</small></div>}</section>
    </>}
  </main>;
}
