import { useCallback, useEffect, useMemo, useState } from 'react';
import { BarChart3, Boxes, CalendarDays, Download, IndianRupee, Landmark, ReceiptIndianRupee, RefreshCw, Scale, ShoppingCart, Users } from 'lucide-react';
import { api, ApiRequestError, type ReportsBootstrap } from '../lib/api';
import { useStation } from '../components/StationProvider';

const money=(value:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(value);
const quantity=(value:number)=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:2}).format(value);
const today=()=>new Date().toLocaleDateString('en-CA');
const monthStart=()=>{const date=new Date();date.setDate(1);return date.toLocaleDateString('en-CA');};
const csvCell=(value:string|number)=>`"${String(value).replaceAll('"','""')}"`;

function Bars({rows}:{rows:Array<{label:string;value:number;detail:string}>}){const high=Math.max(...rows.map(row=>row.value),1);return <div className="report-bars">{rows.length?rows.map(row=><div key={row.label}><span><b>{row.label}</b><small>{row.detail}</small></span><i><em style={{width:`${Math.max((row.value/high)*100,row.value?2:0)}%`}}/></i><strong>{money(row.value)}</strong></div>):<p className="empty-copy">No activity in this period.</p>}</div>}

export function ReportsPage(){
  const {selectedStationId,selectStation}=useStation();
  const [startDate,setStartDate]=useState(monthStart());const [endDate,setEndDate]=useState(today());const [stationId,setStationId]=useState(selectedStationId);
  const [data,setData]=useState<ReportsBootstrap|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{setData(await api.reportsBootstrap({startDate,endDate,...(stationId?{stationId}:{})}));}catch(item){setError(item instanceof ApiRequestError?item.message:'Unable to prepare reports.');}finally{setLoading(false);}},[startDate,endDate,stationId]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>setStationId(selectedStationId),[selectedStationId]);
  const maxDay=useMemo(()=>Math.max(...(data?.sales.daily.map(row=>row.amount)??[]),1),[data]);
  const exportCsv=()=>{if(!data)return;const rows=[['Product','Code','Quantity','Unit','Revenue'],...data.sales.byProduct.map(row=>[row.product,row.code,row.quantity,row.unit,row.revenue])];const blob=new Blob([rows.map(row=>row.map(csvCell).join(',')).join('\n')],{type:'text/csv'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`fuelledger-sales-${startDate}-${endDate}.csv`;link.click();URL.revokeObjectURL(link.href);};
  return <main className="page reports-page">
    <div className="page-heading"><div><span className="eyebrow">Management reports</span><h1>Clear answers from trusted fuel station data</h1><p>Sales, stock, credit, payables, and posted profitability—together, with one reporting period.</p></div><button className="secondary small" onClick={exportCsv} disabled={!data}><Download size={15}/> Export sales CSV</button></div>
    <section className="report-filter"><div><CalendarDays/><label>From<input type="date" value={startDate} max={endDate} onChange={event=>setStartDate(event.target.value)}/></label><label>To<input type="date" value={endDate} min={startDate} onChange={event=>setEndDate(event.target.value)}/></label><label>Fuel station<select value={stationId} onChange={event=>{setStationId(event.target.value);selectStation(event.target.value);}}><option value="">All fuel stations</option>{data?.stations.map(station=><option key={station.id} value={station.id}>{station.name}</option>)}</select></label><button className="primary small" onClick={()=>void load()}><RefreshCw size={14}/> Refresh</button></div><small>Period figures follow the selected dates. Stock, receivables, and payables show the current position.</small></section>
    {error&&<div className="form-error">{error}</div>}
    {loading&&!data?<div className="loading"><span/><p>Turning ledger activity into reports…</p></div>:data&&<>
      <section className="report-kpis"><div><span><IndianRupee/></span><small>Gross sales</small><b>{money(data.summary.grossSales)}</b><em>{data.summary.transactions} transactions</em></div><div><span><BarChart3/></span><small>Metered volume</small><b>{quantity(data.summary.meteredVolume)} L</b><em>Fuel and metered DEF</em></div><div><span><Boxes/></span><small>Inventory value</small><b>{money(data.summary.inventoryValue)}</b><em>Current configured cost</em></div><div><span><Scale/></span><small>Posted net result</small><b className={data.summary.netProfit<0?'negative':''}>{money(data.summary.netProfit)}</b><em>Revenue − COGS − expenses</em></div></section>
      <section className="report-grid wide"><article className="report-card"><header><div><span className="eyebrow">Sales trend</span><h2>Day by day</h2></div><b>{money(data.summary.grossSales)}</b></header><div className="daily-chart">{data.sales.daily.length?data.sales.daily.map(row=><div key={row.key}><i><em style={{height:`${Math.max((row.amount/maxDay)*100,row.amount?4:0)}%`}}/></i><b>{money(row.amount)}</b><small>{new Date(`${row.date}T00:00:00`).toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</small></div>):<p className="empty-copy">No sales in this period.</p>}</div></article><article className="report-card"><header><div><span className="eyebrow">Collections</span><h2>Payment mix</h2></div></header><Bars rows={data.sales.byPayment.map(row=>({label:row.method,value:row.amount,detail:`${row.transactions} transactions`}))}/></article></section>
      <section className="report-grid"><article className="report-card"><header><div><span className="eyebrow">Product performance</span><h2>Sales by product</h2></div></header><div className="report-table"><div className="report-table-head"><span>Product</span><span>Quantity</span><span>Revenue</span></div>{data.sales.byProduct.slice(0,10).map(row=><div key={row.key}><span><b>{row.product}</b><small>{row.code}</small></span><span>{quantity(row.quantity)} {row.unit.toLowerCase()}</span><strong>{money(row.revenue)}</strong></div>)}</div></article><article className="report-card"><header><div><span className="eyebrow">Current stock</span><h2>Inventory position</h2></div><b>{money(data.summary.inventoryValue)}</b></header><div className="report-table"><div className="report-table-head"><span>Product</span><span>On hand</span><span>Value</span></div>{data.inventory.slice(0,10).map(row=><div key={row.key}><span><b>{row.product}</b><small>{row.station}</small></span><span className={row.quantity<0?'negative':''}>{quantity(row.quantity)} {row.unit.toLowerCase()}</span><strong>{money(row.value)}</strong></div>)}</div></article></section>
      <section className="report-grid"><article className="report-card"><header><div><span className="eyebrow">Customer credit</span><h2>Receivables & ageing</h2></div><b>{money(data.summary.receivables)}</b></header><div className="report-table ageing"><div className="report-table-head"><span>Customer</span><span>Over 30 days</span><span>Outstanding</span></div>{data.customers.length?data.customers.map(row=><div key={row.id}><span><b>{row.customer}</b><small>{row.code} · {row.type}</small></span><span>{money(row.ageing.days31to60+row.ageing.days61to90+row.ageing.days90plus)}</span><strong>{money(row.outstanding)}</strong></div>):<p className="empty-copy">No customer balances.</p>}</div></article><article className="report-card"><header><div><span className="eyebrow">Supplier credit</span><h2>Payables</h2></div><b>{money(data.summary.payables)}</b></header><div className="report-table"><div className="report-table-head"><span>Supplier</span><span>Due</span><span>Outstanding</span></div>{data.payables.length?data.payables.map(row=><div key={row.id}><span><b>{row.supplier}</b><small>{row.invoiceNumber} · {row.station}</small></span><span className={row.overdue?'negative':''}>{new Date(row.dueDate).toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</span><strong>{money(row.outstanding)}</strong></div>):<p className="empty-copy">No open supplier invoices.</p>}</div></article></section>
      <section className="report-grid financial"><article className="report-card pnl-card"><header><div><span className="eyebrow">Financial report</span><h2>Posted profit & loss</h2></div><Landmark/></header><div><span>Revenue<b>{money(data.financial.revenue)}</b></span><span>Cost of goods sold<b>{money(data.financial.cogs)}</b></span><strong>Gross profit<b>{money(data.financial.grossProfit)}</b></strong><span>Operating expenses<b>{money(data.financial.operatingExpenses)}</b></span><strong className="net">Net result<b>{money(data.financial.netProfit)}</b></strong></div><p>Uses journals posted in the selected period. Operations created before Milestone 9 are not retroactively included.</p></article><article className="report-card"><header><div><span className="eyebrow">Operating costs</span><h2>Expenses by category</h2></div><b>{money(data.summary.expenses)}</b></header><Bars rows={data.expenses.map(row=>({label:row.category,value:row.amount,detail:'Recorded expenses'}))}/><div className="report-context"><ShoppingCart/><span><small>Purchases in period</small><b>{money(data.summary.purchases)}</b></span><ReceiptIndianRupee/><span><small>Operating expenses</small><b>{money(data.summary.expenses)}</b></span></div></article></section>
      {!stationId&&data.sales.byStation.length>1&&<section className="report-card station-report"><header><div><span className="eyebrow">Outlet comparison</span><h2>Sales by fuel station</h2></div><Users/></header><Bars rows={data.sales.byStation.map(row=>({label:row.station,value:row.amount,detail:`${row.transactions} transactions · ${row.code}`}))}/></section>}
    </>}
  </main>;
}
