import { useCallback, useEffect, useMemo, useState } from 'react';
import { BarChart3, Boxes, CalendarDays, Download, FileSpreadsheet, IndianRupee, Landmark, Printer, ReceiptIndianRupee, RefreshCw, Scale, ShoppingCart, Users } from 'lucide-react';
import { api, ApiRequestError, type ReportsBootstrap } from '../lib/api';
import { useStation } from '../components/StationProvider';
import { Link } from 'react-router-dom';

const money=(value:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(value);
const quantity=(value:number)=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:2}).format(value);
const today=()=>new Date().toLocaleDateString('en-CA');
const monthStart=()=>{const date=new Date();date.setDate(1);return date.toLocaleDateString('en-CA');};
type Cell=string|number|boolean|null|undefined;
type ReportGroup='Daily control'|'Stock & purchases'|'Money & tax'|'Evidence & audit'|'Accounting'|'Tax working papers'|'Compliance registers'|'Intelligence & forecasts'|'Data rooms';
type DownloadableReport={id:string;title:string;description:string;group:ReportGroup;columns:string[];rows:Cell[][];warning?:string|undefined};
const safeText=(value:Cell)=>{const text=String(value??'');return /^[=+\-@]/.test(text)?`'${text}`:text;};
const csvCell=(value:Cell)=>`"${safeText(value).replaceAll('"','""')}"`;
const html=(value:Cell)=>safeText(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const date=(value:string|null)=>value?new Date(value).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'—';
const createReportLibrary=(data:ReportsBootstrap):DownloadableReport[]=>{
  const shifts=data.operations.shifts;
  const latestPhysical=new Map<string,ReportsBootstrap['operations']['tankReadings'][number]>();
  for(const row of data.operations.tankReadings)if(!latestPhysical.has(`${row.stationCode}:${row.productCode}`))latestPhysical.set(`${row.stationCode}:${row.productCode}`,row);
  return [
    {id:'daily-owner',title:'Daily owner report',description:'One-page position across sales, stock, money and unresolved work.',group:'Daily control',columns:['Measure','Value'],rows:[['Gross sales',data.summary.grossSales],['Transactions',data.summary.transactions],['Metered volume (L)',data.summary.meteredVolume],['Purchases',data.summary.purchases],['Expenses',data.summary.expenses],['Receivables',data.summary.receivables],['Payables',data.summary.payables],['Inventory value',data.summary.inventoryValue],['Posted net result',data.summary.netProfit],['Open shifts',shifts.filter(row=>row.status!=='CLOSED').length],['Unreconciled shifts',shifts.filter(row=>!row.reconciledAt).length]]},
    {id:'shift-closure',title:'Shift closure report',description:'Exact shift status, staff, sales, cash and closure evidence.',group:'Daily control',columns:['Shift','Station','Manager','Opened','Closed','Status','Opening cash','Closing cash','Sales','Notes'],rows:shifts.map(row=>[row.shiftNumber,row.station,row.manager,date(row.openedAt),date(row.closedAt),row.status,row.openingCash,row.closingCash,row.sales,row.notes])},
    {id:'shift-reconciliation',title:'Shift reconciliation report',description:'Expected versus actual collection and the recorded decision.',group:'Daily control',columns:['Shift','Station','Expected','Actual','Variance','Reconciled at','Reconciled by','Notes'],rows:shifts.map(row=>[row.shiftNumber,row.station,row.expectedCollection,row.actualCollection,row.variance,date(row.reconciledAt),row.reconciledBy,row.notes])},
    {id:'sales',title:'Daily sales report',description:'Product quantities, revenue and tax-control classification.',group:'Daily control',columns:['Product','Code','Quantity','Unit','Revenue','Tax treatment'],rows:data.sales.byProduct.map(row=>{const tax=data.tax.rows.find(item=>item.code===row.code);return[row.product,row.code,row.quantity,row.unit,row.revenue,tax?.treatment??'REVIEW_REQUIRED'];})},
    {id:'collections',title:'Collection reconciliation',description:'Recorded collection by tender with shift-level differences.',group:'Daily control',columns:['Shift','Station','Payment method','Expected','Actual','Adjustment','Variance','Reason'],rows:shifts.flatMap(shift=>shift.collections.map(row=>[shift.shiftNumber,shift.station,row.paymentMethod,row.expected,row.actual,row.adjustment,row.variance,row.reason]))},
    {id:'stock',title:'Stock position report',description:'Current recorded quantity and value by station and product.',group:'Stock & purchases',columns:['Station','Product','Code','Quantity','Unit','Unit cost','Value'],rows:data.inventory.map(row=>[row.station,row.product,row.code,row.quantity,row.unit,row.purchasePrice,row.value])},
    {id:'wet-stock',title:'Wet-stock reconciliation',description:'Latest physical readings beside current book stock; timing is always disclosed.',group:'Stock & purchases',columns:['Station','Product','Physical stock','Physical reading time','Current book stock','Variance','Timing basis'],rows:data.inventory.map(row=>{const reading=latestPhysical.get(`${row.stationCode}:${row.code}`);return[row.station,row.product,reading?.physicalStock??null,date(reading?.recordedAt??null),row.quantity,reading?reading.physicalStock-row.quantity:null,'Physical reading and current book stock may have different timestamps'];}),warning:'Do not approve a stock adjustment from this export unless the physical and book snapshots use the same cutoff time.'},
    {id:'tank-density',title:'Tank dip and density register',description:'Physical stock, dip and density readings with recorder identity.',group:'Stock & purchases',columns:['Station','Tank','Product','Physical stock','Dip','Density','Recorded at','Recorded by'],rows:data.operations.tankReadings.map(row=>{const density=data.operations.densityReadings.find(item=>item.stationCode===row.stationCode&&item.tank===row.tank&&item.recordedAt<=row.recordedAt);return[row.station,row.tank,row.product,row.physicalStock,row.dipReading,density?.density??null,date(row.recordedAt),row.recordedBy];})},
    {id:'nozzle-totalizer',title:'Nozzle and totalizer register',description:'Opening, closing and test-delivery readings for every reported shift.',group:'Stock & purchases',columns:['Shift','Station','Dispenser','Nozzle','Product','Opening','Closing','Test quantity','Test returned'],rows:shifts.flatMap(shift=>shift.nozzles.map(row=>[shift.shiftNumber,shift.station,row.dispenser,row.nozzle,row.product,row.opening,row.closing,row.testing,row.testingReturned]))},
    {id:'purchase-delivery',title:'Purchase and delivery report',description:'Supplier invoice, receipt timing, quantities, tax and payment position.',group:'Stock & purchases',columns:['Invoice','Supplier','Station','Invoice date','Received at','Due date','Status','Subtotal','Tax','Total','Paid'],rows:data.operations.purchases.map(row=>[row.invoiceNumber,row.supplier,row.station,date(row.invoiceDate),date(row.receivedAt),date(row.dueDate),row.status,row.subtotal,row.taxAmount,row.totalAmount,row.paidAmount])},
    {id:'customer-outstanding',title:'Customer outstanding report',description:'Customer-level balance and ageing for collection follow-up.',group:'Money & tax',columns:['Customer','Code','Current','1–30 days','31–60 days','61–90 days','90+ days','Outstanding'],rows:data.customers.map(row=>[row.customer,row.code,row.ageing.current,row.ageing.days1to30,row.ageing.days31to60,row.ageing.days61to90,row.ageing.days90plus,row.outstanding])},
    {id:'supplier-outstanding',title:'Supplier outstanding report',description:'Open invoices, due dates and overdue status.',group:'Money & tax',columns:['Supplier','Invoice','Station','Due date','Outstanding','Overdue'],rows:data.payables.map(row=>[row.supplier,row.invoiceNumber,row.station,date(row.dueDate),row.outstanding,row.overdue])},
    {id:'expenses',title:'Expense report',description:'Operating spend by category for the selected period.',group:'Money & tax',columns:['Category','Amount'],rows:data.expenses.map(row=>[row.category,row.amount])},
    {id:'profit-loss',title:'Profit and loss report',description:'Posted revenue, cost and result with completeness warnings.',group:'Money & tax',columns:['Account','Amount'],rows:[['Revenue',data.financial.revenue],['Cost of goods sold',data.financial.cogs],['Gross profit',data.financial.grossProfit],['Operating expenses',data.financial.operatingExpenses],['Net result',data.financial.netProfit]],warning:data.quality.missingCostReason??data.quality.incompleteReason??undefined},
    {id:'ledgers',title:'Customer and supplier ledgers',description:'Source-linked customer movements and supplier payments.',group:'Money & tax',columns:['Party type','Party','Station','Date','Entry','Reference','Debit / payment','Due date','Recorded by'],rows:[...data.operations.customerLedger.map(row=>['Customer',row.customer,row.station,date(row.occurredAt),row.description,row.referenceNo??row.sourceId,row.amount,date(row.dueDate),row.createdBy]),...data.operations.supplierPayments.map(row=>['Supplier',row.supplier,row.station,date(row.paidAt),'Payment',row.referenceNo??row.invoiceNumber,-row.amount,'—',row.createdBy])]},
    {id:'tax-separation',title:'GST and petroleum-tax separation',description:'Turnover split for accountant review; never presented as a filed return.',group:'Money & tax',columns:['Product','Code','HSN','Treatment','Quantity','Turnover'],rows:data.tax.rows.map(row=>[row.product,row.code,row.hsnCode,row.treatment,row.quantity,row.turnover]),warning:data.tax.warning},
    {id:'audit-history',title:'Approval history',description:'What was requested, who decided it and whether it was completed.',group:'Evidence & audit',columns:['Fuel station','Request','Current position','Reason','Requested by','Requested at','Decided by','Decided at','Decision note','Completed at'],rows:data.operations.approvals.map(row=>[row.station,row.actionType.toLowerCase().replaceAll('_',' '),row.status.toLowerCase().replaceAll('_',' '),row.reason,row.requestedBy,date(row.requestedAt),row.decidedBy,date(row.decidedAt),row.decisionNote,date(row.executedAt)])},
    {id:'trial-balance',title:'Trial balance',description:'Debit, credit and normal balance for every posted account.',group:'Accounting',columns:['Account code','Account name','Type','Debit','Credit','Balance'],rows:data.financial.accounts.map(row=>[row.code,row.name,row.type,row.debit,row.credit,row.balance]),warning:'Includes posted journals in the selected period only.'},
    {id:'general-ledger',title:'General ledger',description:'Posted account movements in chronological order.',group:'Accounting',columns:['Date','Fuel station','Reference','Description','Entry type','Account','Account name','Debit','Credit','Notes','Created by'],rows:data.operations.accountingEntries.map(row=>[date(row.date),row.station,row.reference,row.description,row.sourceType.toLowerCase().replaceAll('_',' '),row.accountCode,row.accountName,row.debit,row.credit,row.memo,row.createdBy])},
    {id:'cash-book',title:'Cash book',description:'Posted movements through the Cash on Hand account.',group:'Accounting',columns:['Date','Station','Reference','Description','Debit','Credit','Source','Created by'],rows:data.operations.accountingEntries.filter(row=>row.accountCode==='1000').map(row=>[date(row.date),row.station,row.reference,row.description,row.debit,row.credit,row.sourceType,row.createdBy])},
    {id:'bank-book',title:'Bank and clearing book',description:'Posted UPI, card and other non-cash collection movements.',group:'Accounting',columns:['Date','Station','Account','Reference','Description','Debit','Credit','Source','Created by'],rows:data.operations.accountingEntries.filter(row=>['1010','1020','1030'].includes(row.accountCode)).map(row=>[date(row.date),row.station,row.accountName,row.reference,row.description,row.debit,row.credit,row.sourceType,row.createdBy]),warning:'Clearing accounts are not proof of bank settlement until matched to a bank statement.'},
    {id:'bank-reconciliation',title:'Bank reconciliation working paper',description:'Book-side balances awaiting bank-statement matching.',group:'Accounting',columns:['Account','Book balance','Statement balance','Difference','Status'],rows:data.financial.accounts.filter(row=>['1010','1020','1030'].includes(row.code)).map(row=>[`${row.code} · ${row.name}`,row.balance,null,null,'BANK STATEMENT NOT IMPORTED']),warning:'FuelNerve has not received a bank statement for this period. No reconciled bank balance is asserted.'},
    {id:'gst-sales-working',title:'GST outward-supply working report',description:'Configured GST product turnover for return preparation.',group:'Tax working papers',columns:['Product','Code','HSN','Configured treatment','Quantity','Turnover'],rows:data.tax.rows.filter(row=>row.treatment.startsWith('GST')).map(row=>[row.product,row.code,row.hsnCode,row.treatment,row.quantity,row.turnover]),warning:'Working paper only. Confirm place of supply, invoice classification and configured tax rate before filing.'},
    {id:'gst-purchase-working',title:'GST purchase and ITC working report',description:'Supplier invoice lines with recorded HSN and tax rates.',group:'Tax working papers',columns:['Invoice','Supplier','Station','Invoice date','Description','Product','HSN','Quantity','Unit cost','Tax rate','Line total'],rows:data.operations.purchases.flatMap(invoice=>invoice.lines.filter(line=>line.taxRate>0).map(line=>[invoice.invoiceNumber,invoice.supplier,invoice.station,date(invoice.invoiceDate),line.description,line.product,line.hsnCode,line.quantity,line.unitCost,line.taxRate,line.lineTotal])),warning:'This does not establish ITC eligibility or GSTR-2B matching.'},
    {id:'gst-summary-working',title:'GST turnover working summary',description:'GST-review turnover separated from petroleum-tax turnover.',group:'Tax working papers',columns:['Classification','Turnover'],rows:[['Configured GST / GST review turnover',data.tax.gstReviewTurnover],['State petroleum-tax review turnover',data.tax.stateVatTurnover],['Total recorded turnover',data.tax.gstReviewTurnover+data.tax.stateVatTurnover]],warning:data.tax.warning},
    {id:'state-vat-working',title:'State VAT petroleum working report',description:'Fuel-category quantities and turnover for state-specific review.',group:'Tax working papers',columns:['Product','Code','Quantity','Turnover','Treatment'],rows:data.tax.rows.filter(row=>row.treatment==='STATE_PETROLEUM_TAX').map(row=>[row.product,row.code,row.quantity,row.turnover,row.treatment]),warning:'Apply the station state, effective tax rate, cess and dealer-commission rules outside this report before filing.'},
    {id:'tds-register',title:'TDS register',description:'Controlled template for deductions, deposits and return references.',group:'Compliance registers',columns:['Deductee','PAN','Section','Transaction date','Gross amount','Rate','TDS amount','Deduction date','Deposit date','Challan','Return quarter','Certificate status'],rows:[],warning:'No TDS source records are stored in FuelNerve yet. This download is a blank controlled template, not evidence of nil liability.'},
    {id:'fixed-assets',title:'Fixed asset and depreciation register',description:'Controlled template for dispensers, tanks and other capital assets.',group:'Compliance registers',columns:['Asset ID','Asset','Category','Station','Acquisition date','Cost','Useful life','Depreciation method','Accumulated depreciation','Written-down value','Disposal date'],rows:[],warning:'No fixed-asset records are stored in FuelNerve yet. Obtain accountant review before calculating depreciation.'},
    {id:'licence-calendar',title:'Licence and renewal calendar',description:'Controlled template for licences, NOCs, insurance and registrations.',group:'Compliance registers',columns:['Licence or approval','Authority','Station','Reference number','Issued date','Expiry date','Renewal owner','Status','Document reference'],rows:[],warning:'No licence records are stored in FuelNerve yet. An empty export must not be interpreted as full compliance.'},
    {id:'legal-metrology',title:'Legal Metrology register',description:'Controlled template for dispenser verification and re-verification.',group:'Compliance registers',columns:['Station','Dispenser','Nozzle','Certificate number','Verification date','Valid until','Seal status','Officer or agency','Repair date','Re-verification date','Document reference'],rows:[],warning:'No Legal Metrology verification records are stored in FuelNerve yet.'},
    {id:'safety-register',title:'Safety inspection register',description:'Controlled template for recurring safety checks and corrective actions.',group:'Compliance registers',columns:['Inspection date','Station','Checklist','Inspector','Result','Non-conformity','Corrective action','Owner','Due date','Closed date','Evidence'],rows:[],warning:'No safety inspections are stored in FuelNerve yet. This template does not replace the required inspection process.'},
    {id:'incident-register',title:'Incident and near-miss register',description:'Controlled template for events, response and closure evidence.',group:'Compliance registers',columns:['Incident ID','Date and time','Station','Type','Description','People involved','Quantity affected','Immediate response','Authority or OMC informed','Corrective action','Status','Evidence'],rows:[],warning:'No incident records are stored in FuelNerve yet. An empty export is not a declaration that no incidents occurred.'},
    {id:'omc-reconciliation',title:'OMC and supplier reconciliation',description:'Invoice-to-receipt quantity, value and payment working report.',group:'Compliance registers',columns:['Supplier','Invoice','Station','Product','Unit','Invoice date','Received at','Invoiced quantity','Received quantity','Quantity difference','Invoice total','Paid','Outstanding','Status'],rows:data.operations.purchases.flatMap(invoice=>invoice.lines.map(line=>{const received=line.productCode&&line.unit?invoice.receivedLines.filter(item=>item.productCode===line.productCode&&item.unit===line.unit).reduce((total,item)=>total+item.quantity,0):null;return[invoice.supplier,invoice.invoiceNumber,invoice.station,line.product??line.description,line.unit,date(invoice.invoiceDate),date(invoice.receivedAt),line.quantity,received,received===null?null:received-line.quantity,invoice.totalAmount,invoice.paidAmount,invoice.totalAmount-invoice.paidAmount,invoice.status];})),warning:'Treat suppliers as OMCs only after supplier classification is configured. Quantity differences are calculated only for matching product codes and units.'},
    {id:'specialist-reports',title:'Nerve Intelligence report',description:'A clear summary of what needs attention and what to do next.',group:'Intelligence & forecasts',columns:['Date','Fuel station','Priority','What needs attention','Why it matters','What to do next','Supporting record'],rows:data.intelligence.specialistReports.map(row=>[date(row.briefingDate),row.station,row.priority,row.finding,row.explanation,row.nextStep,row.supportingRecord]),warning:'Review the supporting record before making a financial or stock decision.'},
    {id:'runout-forecast',title:'Stock runout outlook',description:'How long current stock may last, based on recent recorded sales.',group:'Intelligence & forecasts',columns:['Fuel station','Product','Current stock','Unit','Recent daily sales','Estimated days left','Outlook','How this was calculated'],rows:data.intelligence.runoutForecasts.map(row=>[row.station,row.product,row.currentQuantity,row.unit,row.averageDailyConsumption,row.estimatedDaysRemaining,row.status,row.assumption]),warning:'Use this as an early warning only. Confirm current stock and upcoming deliveries before ordering.'},
    {id:'cash-flow-forecast',title:'Cash-flow forecast',description:'Conservative 7-day and 30-day view from posted liquid accounts and supplier due dates.',group:'Intelligence & forecasts',columns:['As of','Opening liquid position','Supplier dues in 7 days','Position after 7 days','Supplier dues in 30 days','Position after 30 days','Customer receipts included','Basis'],rows:[[date(data.intelligence.cashFlowForecast.asOf),data.intelligence.cashFlowForecast.openingLiquidPosition,data.intelligence.cashFlowForecast.supplierPaymentsDueIn7Days,data.intelligence.cashFlowForecast.conservativePositionAfter7Days,data.intelligence.cashFlowForecast.supplierPaymentsDueIn30Days,data.intelligence.cashFlowForecast.conservativePositionAfter30Days,data.intelligence.cashFlowForecast.customerReceiptsIncluded,data.intelligence.cashFlowForecast.assumption]],warning:data.intelligence.cashFlowForecast.warning},
    {id:'cross-station',title:'Cross-station comparison',description:'Comparable operating and money positions for every fuel station in the permitted scope.',group:'Intelligence & forecasts',columns:['Station','Code','Sales','Transactions','Inventory value','Receivables','Payables','Shift variance','Shifts reviewed'],rows:data.intelligence.stationComparison.map(row=>[row.station,row.stationCode,row.sales,row.transactions,row.inventoryValue,row.receivables,row.payables,row.shiftVariance,row.shiftsReviewed]),warning:data.intelligence.stationComparison.length<2?'Only one permitted station is available; no cross-station conclusion can be drawn.':undefined},
    {id:'investigation-packs',title:'Owner investigation report',description:'Plain-language findings from investigations requested by the owner.',group:'Intelligence & forecasts',columns:['Date','Fuel station','Question reviewed','Requested by','What we found','Information still missing','What to do next'],rows:data.intelligence.investigationPacks.map(row=>[date(row.createdAt),row.station,row.subject,row.requestedBy,row.findings,row.informationMissing,row.nextStep]),warning:'Re-run the investigation if the underlying records have changed.'},
    {id:'anomaly-trends',title:'Attention history',description:'Important alerts over time, with their current position and supporting record.',group:'Intelligence & forecasts',columns:['Date','Fuel station','Priority','What happened','Why it matters','Supporting record','Current position','Resolved on'],rows:data.intelligence.anomalyTrends.map(row=>[date(row.createdAt),row.station,row.severity,row.title,row.message,row.supportingRecord,row.status,date(row.resolvedAt)]),warning:'This report includes recorded alerts only. Review the supporting records before taking action.'},
    {id:'accountant-data-room',title:'Accountant data room',description:'Readable accounting records covering journals, customers, suppliers, payments and tax working data.',group:'Data rooms',columns:['Record type','Date','Fuel station','Party or account','Reference','Amount or debit','Paid or credit','Current position','Description'],rows:[...data.operations.accountingEntries.map(row=>['General ledger',date(row.date),row.station,`${row.accountCode} · ${row.accountName}`,row.reference,row.debit,row.credit,'Posted',row.description]),...data.operations.customerLedger.map(row=>['Customer ledger',date(row.occurredAt),row.station,row.customer,row.referenceNo??'—',row.amount,0,row.disputedAt?'Disputed':'Recorded',row.description]),...data.operations.purchases.map(row=>['Supplier invoice',date(row.invoiceDate),row.station,row.supplier,row.invoiceNumber,row.totalAmount,row.paidAmount,row.status.toLowerCase().replaceAll('_',' '),`Due ${date(row.dueDate)}`]),...data.operations.supplierPayments.map(row=>['Supplier payment',date(row.paidAt),row.station,row.supplier,row.referenceNo??row.invoiceNumber,0,row.amount,row.paymentMethod.toLowerCase().replaceAll('_',' '),`Recorded by ${row.createdBy}`]),...data.tax.rows.map(row=>['Tax working row','—',data.filter.station?.name??'All permitted fuel stations',row.product,row.hsnCode,row.turnover,0,row.treatment.toLowerCase().replaceAll('_',' '),`${row.quantity} units`])],warning:'This package contains management records, not filed returns or an accountant’s assurance. Review completeness, tax treatment and bank matching before sharing.'},
    {id:'auditor-data-room',title:'Auditor evidence room',description:'Readable operational evidence covering shifts, readings, approvals and owner alerts.',group:'Data rooms',columns:['Record type','Date','Fuel station','Subject','Current position','Amount or quantity','Supporting record','Detail'],rows:[...data.operations.shifts.map(row=>['Shift',date(row.openedAt),row.station,`Shift ${row.shiftNumber}`,row.status,row.variance,row.reconciledAt?'Reconciliation completed':'Reconciliation pending',row.notes]),...data.operations.tankReadings.map(row=>['Tank reading',date(row.recordedAt),row.station,`${row.tank} · ${row.product}`,'Recorded',row.physicalStock,`Recorded by ${row.recordedBy}`,row.notes]),...data.operations.densityReadings.map(row=>['Density reading',date(row.recordedAt),row.station,`${row.tank} · ${row.product}`,'Recorded',row.density,`Recorded by ${row.recordedBy}`,'Density reading']),...data.operations.approvals.map(row=>['Owner approval',date(row.requestedAt),row.station,row.actionType.toLowerCase().replaceAll('_',' '),row.status.toLowerCase(),null,row.decidedBy?`Decided by ${row.decidedBy}`:'Owner decision pending',row.reason]),...data.intelligence.specialistReports.map(row=>['Nerve Intelligence',date(row.calculatedAt),row.station,row.finding,row.priority,null,row.supportingRecord,`${row.explanation} ${row.nextStep}`]),...data.intelligence.investigationPacks.map(row=>['Owner investigation',date(row.createdAt),row.station,row.subject,'Reviewed',null,`Requested by ${row.requestedBy}`,`${row.findings} ${row.nextStep}`]),...data.intelligence.anomalyTrends.map(row=>['Owner alert',date(row.createdAt),row.station,row.title,row.status,null,row.supportingRecord,row.message])],warning:'Access remains limited to permitted fuel stations. Confirm that records are current before relying on this report.'},
  ];
};

export function ReportLibrary({data,startDate,endDate}:{data:ReportsBootstrap;startDate:string;endDate:string}){
  const reports=createReportLibrary(data);const [group,setGroup]=useState<ReportGroup|'All'>('All');
  const visible=group==='All'?reports:reports.filter(report=>report.group===group);
  const download=(report:DownloadableReport)=>{const metadata=[['FuelNerve report',report.title],['Period',`${startDate} to ${endDate}`],['Station',data.filter.station?.name??'All permitted fuel stations'],['Generated at',new Date().toISOString()],['Status','Management report — review before filing'],...(report.warning?[['Warning',report.warning]]:[])];const csv=[...metadata,[],report.columns,...report.rows].map(row=>row.map(csvCell).join(',')).join('\n');const blob=new Blob(['\ufeff',csv],{type:'text/csv;charset=utf-8'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`fuelnerve-${report.id}-${startDate}-${endDate}.csv`;link.click();URL.revokeObjectURL(link.href);};
  const print=(report:DownloadableReport)=>{const popup=window.open('','_blank');if(!popup)return;popup.opener=null;popup.document.write(`<!doctype html><html><head><title>${html(report.title)}</title><style>body{font-family:Arial,sans-serif;color:#173f35;padding:28px}h1{margin-bottom:4px}p{color:#5f7169}.meta{font-size:12px;margin:18px 0}.warning{padding:10px;background:#fff4dc;color:#76520b}table{width:100%;border-collapse:collapse;font-size:11px}th,td{padding:7px;border:1px solid #dfe6e1;text-align:left}th{background:#edf5f1}@media print{body{padding:0}}</style></head><body><h1>${html(report.title)}</h1><p>${html(report.description)}</p><div class="meta">${html(data.filter.station?.name??'All permitted fuel stations')} · ${html(startDate)} to ${html(endDate)} · Generated ${html(new Date().toLocaleString('en-IN'))}</div>${report.warning?`<p class="warning">${html(report.warning)}</p>`:''}<table><thead><tr>${report.columns.map(column=>`<th>${html(column)}</th>`).join('')}</tr></thead><tbody>${report.rows.map(row=>`<tr>${row.map(cell=>`<td>${html(cell)}</td>`).join('')}</tr>`).join('')}</tbody></table><script>window.print();<\/script></body></html>`);popup.document.close();};
  return <section className="report-library"><header><div><span className="eyebrow">Owner downloads</span><h2>Owner report library</h2><p>Choose a report, then download the working data or save a clean PDF.</p></div><b>{reports.length} reports ready</b></header><div className="report-tabs">{(['All','Daily control','Stock & purchases','Money & tax','Accounting','Tax working papers','Compliance registers','Intelligence & forecasts','Data rooms','Evidence & audit'] as const).map(item=><button key={item} className={group===item?'active':''} onClick={()=>setGroup(item)}>{item}</button>)}</div><div className="report-library-grid">{visible.map(report=><article key={report.id}><FileSpreadsheet/><div><h3>{report.title}</h3><p>{report.description}</p><small>{report.rows.length} {report.rows.length===1?'row':'rows'}{report.warning?' · Review note included':''}</small></div><footer><button onClick={()=>download(report)}><Download/> CSV</button><button onClick={()=>print(report)}><Printer/> PDF</button></footer></article>)}</div></section>;
}

function Bars({rows}:{rows:Array<{label:string;value:number;detail:string}>}){const high=Math.max(...rows.map(row=>row.value),1);return <div className="report-bars">{rows.length?rows.map(row=><div key={row.label}><span><b>{row.label}</b><small>{row.detail}</small></span><i><em style={{width:`${Math.max((row.value/high)*100,row.value?2:0)}%`}}/></i><strong>{money(row.value)}</strong></div>):<p className="empty-copy">No activity in this period.</p>}</div>}

export function ReportsPage(){
  const {selectedStationId,selectStation}=useStation();
  const [startDate,setStartDate]=useState(monthStart());const [endDate,setEndDate]=useState(today());const [stationId,setStationId]=useState(selectedStationId);
  const [data,setData]=useState<ReportsBootstrap|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{setData(await api.reportsBootstrap({startDate,endDate,...(stationId?{stationId}:{})}));}catch(item){setError(item instanceof ApiRequestError?item.message:'Unable to prepare reports.');}finally{setLoading(false);}},[startDate,endDate,stationId]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>setStationId(selectedStationId),[selectedStationId]);
  const maxDay=useMemo(()=>Math.max(...(data?.sales.daily.map(row=>row.amount)??[]),1),[data]);
  return <main className="page reports-page">
    <div className="page-heading"><div><span className="eyebrow">Management reports</span><h1>Clear answers from trusted fuel station data</h1><p>Sales, stock, credit, payables, and posted profitability—together, with one reporting period.</p></div><Link className="secondary small" to="/reports/downloads"><Download size={15}/> Download reports</Link></div>
    <section className="report-filter"><div><CalendarDays/><label>From<input type="date" value={startDate} max={endDate} onChange={event=>setStartDate(event.target.value)}/></label><label>To<input type="date" value={endDate} min={startDate} onChange={event=>setEndDate(event.target.value)}/></label><label>Fuel station<select value={stationId} onChange={event=>{setStationId(event.target.value);selectStation(event.target.value);}}><option value="">All fuel stations</option>{data?.stations.map(station=><option key={station.id} value={station.id}>{station.name}</option>)}</select></label><button className="primary small" onClick={()=>void load()}><RefreshCw size={14}/> Refresh</button></div><small>Period figures follow the selected dates. Stock, receivables, and payables show the current position.</small></section>
    {error&&<div className="form-error">{error}</div>}
    {loading&&!data?<div className="loading"><span/><p>Turning ledger activity into reports…</p></div>:data&&<>
      <section className="report-kpis"><div><span><IndianRupee/></span><small>Gross sales</small><b>{money(data.summary.grossSales)}</b><em>{data.summary.transactions} transactions</em></div><div><span><BarChart3/></span><small>Metered volume</small><b>{quantity(data.summary.meteredVolume)} L</b><em>Fuel and metered DEF</em></div><div><span><Boxes/></span><small>Inventory value</small><b>{money(data.summary.inventoryValue)}</b><em>Current configured cost</em></div><div><span><Scale/></span><small>Posted net result</small><b className={data.summary.netProfit<0?'negative':''}>{money(data.summary.netProfit)}</b><em>Revenue − COGS − expenses</em></div></section>
      <section className="report-grid wide"><article className="report-card"><header><div><span className="eyebrow">Sales trend</span><h2>Day by day</h2></div><b>{money(data.summary.grossSales)}</b></header><div className="daily-chart">{data.sales.daily.length?data.sales.daily.map(row=><div key={row.key}><i><em style={{height:`${Math.max((row.amount/maxDay)*100,row.amount?4:0)}%`}}/></i><b>{money(row.amount)}</b><small>{new Date(`${row.date}T00:00:00`).toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</small></div>):<p className="empty-copy">No sales in this period.</p>}</div></article><article className="report-card"><header><div><span className="eyebrow">Collections</span><h2>Payment mix</h2></div></header><Bars rows={data.sales.byPayment.map(row=>({label:row.method,value:row.amount,detail:`${row.transactions} transactions`}))}/></article></section>
      <section className="report-grid"><article className="report-card"><header><div><span className="eyebrow">Product performance</span><h2>Sales by product</h2></div></header><div className="report-table"><div className="report-table-head"><span>Product</span><span>Quantity</span><span>Revenue</span></div>{data.sales.byProduct.slice(0,10).map(row=><div key={row.key}><span><b>{row.product}</b><small>{row.code}</small></span><span>{quantity(row.quantity)} {row.unit.toLowerCase()}</span><strong>{money(row.revenue)}</strong></div>)}</div></article><article className="report-card"><header><div><span className="eyebrow">Current stock</span><h2>Inventory position</h2></div><b>{money(data.summary.inventoryValue)}</b></header><div className="report-table"><div className="report-table-head"><span>Product</span><span>On hand</span><span>Value</span></div>{data.inventory.slice(0,10).map(row=><div key={row.key}><span><b>{row.product}</b><small>{row.station}</small></span><span className={row.quantity<0?'negative':''}>{quantity(row.quantity)} {row.unit.toLowerCase()}</span><strong>{money(row.value)}</strong></div>)}</div></article></section>
      <section className="report-grid"><article className="report-card"><header><div><span className="eyebrow">Customer credit</span><h2>Receivables & ageing</h2></div><b>{money(data.summary.receivables)}</b></header><div className="report-table ageing"><div className="report-table-head"><span>Customer</span><span>Over 30 days</span><span>Outstanding</span></div>{data.customers.length?data.customers.map(row=><div key={row.id}><span><b>{row.customer}</b><small>{row.code} · {row.type}</small></span><span>{money(row.ageing.days31to60+row.ageing.days61to90+row.ageing.days90plus)}</span><strong>{money(row.outstanding)}</strong></div>):<p className="empty-copy">No customer balances.</p>}</div></article><article className="report-card"><header><div><span className="eyebrow">Supplier credit</span><h2>Payables</h2></div><b>{money(data.summary.payables)}</b></header><div className="report-table"><div className="report-table-head"><span>Supplier</span><span>Due</span><span>Outstanding</span></div>{data.payables.length?data.payables.map(row=><div key={row.id}><span><b>{row.supplier}</b><small>{row.invoiceNumber} · {row.station}</small></span><span className={row.overdue?'negative':''}>{new Date(row.dueDate).toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</span><strong>{money(row.outstanding)}</strong></div>):<p className="empty-copy">No open supplier invoices.</p>}</div></article></section>
      <section className="report-grid financial"><article className="report-card pnl-card"><header><div><span className="eyebrow">Financial report</span><h2>Posted profit & loss</h2></div><Landmark/></header><div><span>Revenue<b>{money(data.financial.revenue)}</b></span><span>Cost of goods sold<b>{money(data.financial.cogs)}</b></span><strong>Gross profit<b>{money(data.financial.grossProfit)}</b></strong><span>Operating expenses<b>{money(data.financial.operatingExpenses)}</b></span><strong className="net">Net result<b>{money(data.financial.netProfit)}</b></strong></div><p>Uses journals posted in the selected period. Operations created before Milestone 9 are not retroactively included.</p></article><article className="report-card"><header><div><span className="eyebrow">Operating costs</span><h2>Expenses by category</h2></div><b>{money(data.summary.expenses)}</b></header><Bars rows={data.expenses.map(row=>({label:row.category,value:row.amount,detail:'Recorded expenses'}))}/><div className="report-context"><ShoppingCart/><span><small>Purchases in period</small><b>{money(data.summary.purchases)}</b></span><ReceiptIndianRupee/><span><small>Operating expenses</small><b>{money(data.summary.expenses)}</b></span></div></article></section>
      {!stationId&&data.sales.byStation.length>1&&<section className="report-card station-report"><header><div><span className="eyebrow">Outlet comparison</span><h2>Sales by fuel station</h2></div><Users/></header><Bars rows={data.sales.byStation.map(row=>({label:row.station,value:row.amount,detail:`${row.transactions} transactions · ${row.code}`}))}/></section>}
    </>}
  </main>;
}
