import type { AgentDefinition } from "../../runtime-contracts.ts";
import type { JsonObject } from "../../contracts.ts";
import type { IndustryTerminology } from "../../industry-pack.ts";
import { evidenceAt, fact, fallback, items, packet, scopeInput, validateNarrative } from "./shared.ts";

export function createGenericInventoryWatchAgent(terms: IndustryTerminology): AgentDefinition { return singleToolAgent({ agentKey: "inventory-watch", toolId: "inventory.position.read", description: `Reviews application-calculated ${terms.inventoryUnit} positions across each ${terms.location}.`, terms, build: result => items(result).filter(item => item.status === "LOW" || item.status === "EMPTY" || item.requiresReview === true).map((item, index) => { const location = String(item.locationId ?? "unknown"); return fact(`inventory-${index + 1}`, `${terms.inventoryUnit} ${String(item.status ?? "requires review")}`, item.displayValue ?? item.status ?? null, evidenceAt(result, location)); }) }); }

export function createGenericReceivablesAgent(terms: IndustryTerminology): AgentDefinition { return singleToolAgent({ agentKey: "receivables-watch", toolId: "receivables.ageing.read", description: `Reviews application-calculated ${terms.receivable} ageing.`, terms, build: result => items(result).filter(item => item.requiresReview === true).map((item, index) => { const location = String(item.locationId ?? "unknown"); return fact(`receivable-${index + 1}`, `${terms.customer} balance requires review`, { amount: item.amount ?? 0, ageBucket: item.ageBucket ?? "APPLICATION_DEFINED" }, evidenceAt(result, location)); }) }); }

export function createGenericProfitInsightAgent(terms: IndustryTerminology): AgentDefinition { return singleToolAgent({ agentKey: "profit-insight", toolId: "profit.summary.read", description: `Explains the application's calculated ${terms.profitReport}.`, terms, build: result => items(result).map((item, index) => { const location = String(item.locationId ?? "unknown"); return fact(`profit-${index + 1}`, item.materialChange === true ? `${terms.profitReport} changed materially` : `${terms.profitReport} position`, { revenue: item.revenue ?? 0, cogs: item.cogs ?? 0, expenses: item.expenses ?? 0, netResult: item.netResult ?? 0, materialChange: item.materialChange ?? false }, evidenceAt(result, location)); }) }); }

export function createGenericBusinessAssistantAgent(terms: IndustryTerminology, configuredTools?: Record<string, string>): AgentDefinition {
  const tools: Record<string, string> = configuredTools ?? { inventory: "inventory.position.read", receivables: "receivables.ageing.read", profit: "profit.summary.read" };
  return { agentKey: "business-assistant", agentVersion: "1.0.0", promptVersion: `business-assistant.${terms.packId}@1`, description: "Answers supported questions using one application-owned read capability.", instructions: "Use only supplied facts and evidence. Never calculate business values or infer unavailable answers.", outputSchemaId: "nerve.agent-narrative@1", allowedToolIds: Object.values(tools), maxToolCalls: 1, maxOutputTokens: 350,
    plan(input, context) { const toolId = tools[String(input.intent ?? "")]; return toolId ? [{ toolId, input: scopeInput(input, context.permittedLocationIds) }] : []; },
    buildFacts(results) { if (!results[0]) return { facts: [], evidence: [] }; const result = results[0]; return packet(items(result).map((item, index) => fact(`answer-${index + 1}`, String(item.label ?? "Application fact"), item.value ?? item.displayValue ?? item, result.evidence)), results); },
    validateOutput: validateNarrative, deterministicFallback: facts => fallback("Business assistant", facts) };
}

function singleToolAgent(input: { agentKey: string; toolId: string; description: string; terms: IndustryTerminology; build: (result: Parameters<AgentDefinition["buildFacts"]>[0][number]) => ReturnType<typeof fact>[] }): AgentDefinition {
  return { agentKey: input.agentKey, agentVersion: "1.0.0", promptVersion: `${input.agentKey}.${input.terms.packId}@1`, description: input.description, instructions: "Explain only application-calculated facts. Never perform inventory, receivable, or financial calculations. Cite every claim.", outputSchemaId: "nerve.agent-narrative@1", allowedToolIds: [input.toolId], maxToolCalls: 1, maxOutputTokens: 350, plan: (request, context) => [{ toolId: input.toolId, input: scopeInput(request, context.permittedLocationIds) }], buildFacts: results => packet(input.build(results[0]!), results), validateOutput: validateNarrative, deterministicFallback: facts => fallback(input.description, facts) };
}
