import type { AgentFact, AgentNarrative, FactPacket } from "../../runtime-contracts.ts";
import type { EvidenceReference, JsonObject, ToolResult } from "../../contracts.ts";
import { object, string } from "../../validation.ts";

export const items = (result: ToolResult) => Array.isArray(result.output.items) ? result.output.items.filter((value): value is JsonObject => Boolean(value) && typeof value === "object" && !Array.isArray(value)) : [];
export const evidenceAt = (result: ToolResult, locationId: string) => result.evidence.filter(item => !item.resolverPath?.includes("location=") || item.resolverPath.includes(`location=${encodeURIComponent(locationId)}`));
export const fact = (id: string, label: string, value: AgentFact["value"], evidence: EvidenceReference[]): AgentFact => ({ factId: id, label, value, evidenceIds: evidence.map(item => item.evidenceId) });
export const packet = (facts: AgentFact[], results: ToolResult[]): FactPacket => ({ facts, evidence: unique(results.flatMap(result => result.evidence)) });
export function fallback(headline: string, facts: FactPacket): AgentNarrative { return { headline, summary: facts.facts.length ? `${facts.facts.length} application-calculated item${facts.facts.length === 1 ? "" : "s"} require review.` : "No review items were returned by the application.", claims: facts.facts.map((item, index) => ({ claimId: `claim-${index + 1}`, text: item.label, factIds: [item.factId], evidenceIds: item.evidenceIds })) }; }
export function validateNarrative(value: unknown, path = "narrative"): AgentNarrative { const row = object(value, path); return { headline: string(row.headline, `${path}.headline`), summary: string(row.summary, `${path}.summary`), claims: unknownArray(row.claims, `${path}.claims`).map((claim, index) => { const item = object(claim, `${path}.claims[${index}]`); return { claimId: string(item.claimId, `${path}.claims[${index}].claimId`), text: string(item.text, `${path}.claims[${index}].text`), factIds: unknownArray(item.factIds, `${path}.claims[${index}].factIds`).map((id, i) => string(id, `${path}.claims[${index}].factIds[${i}]`)), evidenceIds: unknownArray(item.evidenceIds, `${path}.claims[${index}].evidenceIds`).map((id, i) => string(id, `${path}.claims[${index}].evidenceIds[${i}]`)) }; }) }; }
export const scopeInput = (input: JsonObject, locationIds: string[]) => ({ locationIds, asOf: typeof input.asOf === "string" ? input.asOf : new Date().toISOString(), ...(typeof input.startDate === "string" ? { startDate: input.startDate } : {}), ...(typeof input.endDate === "string" ? { endDate: input.endDate } : {}) });
function unique(values: EvidenceReference[]) { const seen = new Set<string>(); return values.filter(item => !seen.has(item.evidenceId) && Boolean(seen.add(item.evidenceId))); }
function unknownArray(value: unknown, path: string): unknown[] { if (!Array.isArray(value)) throw new Error(`${path} must be an array.`); return value; }
